document.writeln('	<div class="gotop"><img src="SRC/images/top.svg"></div>');
document.writeln('	');
document.writeln('	<footer class="footer">');
document.writeln('		<div class="inner">');
document.writeln('			<div class="footer-left">');
document.writeln('				<div class="footer-logo"><img src="SRC/images/logo.svg"></div>	');
document.writeln('				<div class="footer-info">');
document.writeln('					客服信箱：jiaojiaojjlady@gmail.com');
document.writeln('				</div>			');
document.writeln('			</div>');
document.writeln('			<div class="footer-right">');
document.writeln('				<div class="footer-link">');
document.writeln('					<a href="privacy.html">隱私權政策</a>');
document.writeln('					<a href="guide.html">購物說明</a>');
document.writeln('				</div>');
document.writeln('				<div class="copyright">©2021  嬌嬌女生技股份有限公司 </div>');
document.writeln('				<a href="http://www.jddt.tw/" target="_blank">Designed by JDDT</a>');
document.writeln('			</div>');
document.writeln('		</div>');
document.writeln('	</footer>');
document.writeln('    <div class="favorite_info jump_info ">');
document.writeln('        已加入願望清單');
document.writeln('    </div>');
document.writeln('    <div class="r-cart">');
document.writeln('    	<div class="close-btn">');
document.writeln('    		<span></span>');
document.writeln('    		<span></span>');
document.writeln('    	</div>');
document.writeln('    	<div class="r-title">購物清單</div>');
document.writeln('    	<div class="item-content">');
document.writeln('			<div class="shop-item">');
document.writeln('			    <div class="shop-info">');
document.writeln('			        <a href="" class="pic"><img src="SRC/images/demo/pro2.jpg"></a> ');
document.writeln('			        <div class="name">');
document.writeln('			        	<span class="two-ellipsis">益生菌水潤氣墊面膜(盒+片)</span>');
document.writeln('			        	<p class="shop-price"><span class="del">NT$19,99</span>NT$9,99</p>');
document.writeln('			        	<p>數量：1</p>');
document.writeln('			        </div>');
document.writeln('			    </div>');
document.writeln('			    ');
document.writeln('			    <div class="shop-del">');
document.writeln('			        <div>x</div>');
document.writeln('			    </div>');
document.writeln('			</div>');
document.writeln('			<div class="shop-item">');
document.writeln('			    <div class="shop-info">');
document.writeln('			        <a href="" class="pic"><img src="SRC/images/demo/pro2.jpg"></a> ');
document.writeln('			        <div class="name">');
document.writeln('			        	<span class="two-ellipsis">益生菌水潤氣墊面膜(盒+片)</span>');
document.writeln('			        	<p class="shop-price"><span class="del">NT$19,99</span>NT$9,99</p>');
document.writeln('			        	<p>數量：1</p>');
document.writeln('			        </div>');
document.writeln('			    </div>');
document.writeln('			    ');
document.writeln('			    <div class="shop-del">');
document.writeln('			        <div>x</div>');
document.writeln('			    </div>');
document.writeln('			</div>	    		');
document.writeln('    	</div>');
document.writeln('');
document.writeln('		<div class="shop-total">');
document.writeln('            <div class="s-t"><span>小計</span><span class="red-font">NT$2,997</span></div>');
document.writeln('        </div>');
document.writeln('        <a class="btn s3" href="shopping.html">前往結帳</a>   	');
document.writeln('    </div>');
document.writeln('');
document.writeln('');
document.writeln('    <!--== all js ==-->');
document.writeln('    <script type="text/javascript" src="SRC/js/1.12.4_jquery.min.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/venobox/venobox.min.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/slick.js"></script>');
document.writeln('    <script src="SRC/js/jquery.zoom.min.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/jquery.twzipcode.min.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/main.js"></script>');
document.writeln('</body>');
document.writeln('');
document.writeln('');
document.writeln('</html>');
