document.writeln('<!DOCTYPE html>');
document.writeln('<html>');
document.writeln('<head>');
document.writeln('    <meta charset="utf-8">');
document.writeln('    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">');
document.writeln('    <meta name="viewport" content="width=device-width initial-scale=1.0 user-scalable=yes">');
document.writeln('    <meta name="format-detection" content="telephone=no">');
document.writeln('    <title>嬌嬌女生技股份有限公司</title>');
document.writeln('    <!--[if IE]>');
document.writeln('    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">``');
document.writeln('    <![endif]-->');
document.writeln('     <link rel="apple-touch-icon" href="SRC/images/favicon/favicon.png">');
document.writeln('    <link rel="shortcut icon" href="SRC/images/favicon/favicon.ico" type="image/x-icon">');
document.writeln('    <link rel="bookmark" href="SRC/images/favicon/favicon.ico" type="image/x-icon">');
document.writeln('    <meta name="Keywords" content="嬌嬌女生技股份有限公司">');
document.writeln('    <meta name="Description" content="">');
document.writeln('    <meta name="Robots" content="All">');
document.writeln('    <meta http-equiv="content-language" content="zh-tw">');
document.writeln('    <!-- og -->');
document.writeln('    <meta property="og:title" content="嬌嬌女生技股份有限公司">');
document.writeln('    <meta property="og:type" content="website">');
document.writeln('    <meta property="og:image" content="SRC/images/og.jpg">');
document.writeln('    <meta property="og:url" content="">');
document.writeln('    <link href="SRC/css/master.css" rel="stylesheet" type="text/css">');
document.writeln('');
document.writeln('</head>');
document.writeln('');
document.writeln('<body >');
document.writeln('');
document.writeln('<header>');
document.writeln('    <div class="header-top">5/11-5/28 新客下單禮-滿1299元送面膜！新會員註冊享 $100 購物金，結帳即可使用。');
document.writeln('    </div>');
document.writeln('');
document.writeln('    ');
document.writeln('    <div class="inner">');
document.writeln('        <div class="logo"><a href="index.html"><img src="SRC/images/logo.svg"></a></div>');
document.writeln('        <div class="header-right">');
document.writeln('            <div class="header-right-top"><a href="member_login.html" class="user-icon"><img src="SRC/images/user.svg"></a><a href="shopping.html" class="shopcart-icon"><img src="SRC/images/cart.svg"><span class="num">1</span></a>');
document.writeln('            <div class="nav-bar show-1024">');
document.writeln('                <span></span>');
document.writeln('                <span></span>');
document.writeln('                <span></span>');
document.writeln('            </div>');
document.writeln('            </div>');
document.writeln('            <nav class="nav">');
document.writeln('                <div class="close-btn">');
document.writeln('                    <span></span>');
document.writeln('                    <span></span>');
document.writeln('                </div>');
document.writeln('                <div class="nav-a"><a href="about.html">關於我們</a></div>');
document.writeln('                <div class="nav-a"><a href="products.html">產品資訊</a>');
document.writeln('                    <div class="nav-drop">');
document.writeln('                        <div class="">');
document.writeln('                            <a href="products.html">面膜系列</a>');
document.writeln('                            <a href="products.html">保養系列</a>   ');
document.writeln('                        </div>');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('                <div class="nav-a"><a href="experience.html">使用者證言</a></div>');
document.writeln('                <div class="nav-a"><a href="news.html">媒體報導</a></div><div class="nav-a"><a href="contact.html">客服中心</a></div>');
document.writeln('            </nav>');
document.writeln('           ');
document.writeln('        </div> ');
document.writeln('    ');
document.writeln('    </div>');
document.writeln('    <div class="mask-bg"></div>');
document.writeln('</header>');
document.writeln('');
