document.writeln('<div class="order-jump O-r-j" action="">');
document.writeln('	<div class="order-jump-inner">');
document.writeln('		<div class="jump-x">X</div>');
document.writeln('		<div class="m-scroll">');
document.writeln('			<form>');
document.writeln('				<div class="title">匯款回覆</div>');
document.writeln('				<div class="form_flex l-30"><span>訂單編號</span>20182723410</div>');
document.writeln('				<div class="form_flex l-30"><span>訂購日期</span>2020-10-10</div>');
document.writeln('				<div class="form_flex l-30"><span>訂單金額</span>$9,999</div>');
document.writeln('				<br>');
document.writeln('				<div class="form_flex">					');
document.writeln('					<input type="text" name="email" placeholder="匯款帳號末五碼" >');
document.writeln('				</div>');
document.writeln('				<div class="form_flex">					');
document.writeln('					<input type="text" name="email" placeholder="匯款金額" >');
document.writeln('				</div>');
document.writeln('				<div class="form_flex date-flex">	<span>匯款日期</span>');
document.writeln('					<div>');
document.writeln('					<input type="date" id="date" name=""><input type="text" name="email" placeholder="匯款時間" >	');
document.writeln('					</div>');
document.writeln('					');
document.writeln('				</div>');
document.writeln('				<div class="f-s">');
document.writeln('					<button type="reset" class="btn s1">重新填寫</button>');
document.writeln('					<button type="submit" class="btn s2">確定送出</button>');
document.writeln('				</div>		');
document.writeln('			</form>');
document.writeln('		</div>	');
document.writeln('	</div>');
document.writeln('</div>');
document.writeln('');