document.write("<footer>");
document.write("		<div class=\"footer-links\">");
document.write("			<div class=\"inner row j-s\">");
document.write("				<a href=\"https:\/\/www.facebook.com\/%E5%9C%8B%E7%AB%8B%E4%B8%AD%E8%88%88%E5%A4%A7%E5%AD%B8%E5%9C%92%E8%97%9D%E5%AD%B8%E7%B3%BB-785832994810827\/\"  Target=\"_blank\"><img src=\"SRC\/images\/fb.svg\"><\/a> ");
document.write("				<div class=\"friendly-link\">");
document.write("					<span>友善連結<\/span>");
document.write("					<div class=\"friendly-link-box\">");
document.write("						<a href=\"\">連結一<\/a>");
document.write("						<a href=\"\">連結二<\/a>						");
document.write("					<\/div>");
document.write("				<\/div>				");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("		<div class=\"inner footer-info row j-s a-c\">");
document.write("			<img class=\"logo\" src=\"SRC\/images\/footer-logo.png\">");
document.write("			<div class=\"footer-info-text row\">");
document.write("				<div>");
document.write("					<span>地址&nbsp;&nbsp;|&nbsp;&nbsp;<a href=\"https:\/\/goo.gl\/maps\/FrridCY6JWS536hKA\" target=\"_blank\">402台中市南區興大路145號  中興大學園藝學系<\/a> <\/span>");
document.write("					<span>信箱&nbsp;&nbsp;|&nbsp;&nbsp;<a href=\"mailto:hort@dragon.nchu.edu.tw\">hort@dragon.nchu.edu.tw<\/a> <\/span>");
document.write("				<\/div>");
document.write("				<div>");
document.write("					<span>電話&nbsp;&nbsp;|&nbsp;&nbsp;<a href=\"tel:+886422840340\">886-4-22840340<\/a> <\/span>");
document.write("					<span>傳真&nbsp;&nbsp;|&nbsp;&nbsp;886-4-22860574<\/span> ");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("		<div class=\"copyright\">");
document.write("			<div class=\"inner row j-s\">");
document.write("				<div class=\"copyright-link\">");
document.write("					<a href=\"\">網站導覽<\/a>");
document.write("					<a href=\"\">隱私聲明<\/a>");
document.write("					<a href=\"\">智財聲明<\/a>");
document.write("					<a href=\"\">網站意見回饋<\/a>");
document.write("				<\/div>");
document.write("				<div class=\"copyright-text\">© 2020 國立中興大學 園藝學系 版權所有 All Rights Reserved. <a class=\"t2\" href=\"http:\/\/www.jddt.tw\/\" target=\"_blank\">Designed by JDDT<\/a><\/div>				");
document.write("			<\/div>");
document.write("");
document.write("		<\/div>");
document.write("	<\/footer>");
document.write("	");
document.write("	<div class=\"go-top\"><i class=\"fa fa-chevron-up\"  aria-hidden=\"true\"><\/i><\/div>");
document.write("    <!--== all js ==-->");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/1.12.4_jquery.min.js\"><\/script>");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/modernizr-custom.js\"><\/script> ");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/main.js\"><\/script>");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/slick.min.js\"><\/script>");
document.write("<\/body>");
document.write("");
document.write("");
document.write("<\/html>");
document.write("");
