document.write("<!doctype html>");
document.write("<html>");
document.write("<head>");
document.write("    <meta charset=\"UTF-8\">");
document.write("    <meta name=\"viewport\" content=\"width=device-width initial-scale=1.0 user-scalable=yes\">");
document.write("    <title>國立中興大學園藝學系<\/title>");
document.write("    <meta name=\"keywords\" content=\"\">");
document.write("    <meta name=\"description\" content=\"\">");
document.write("    <meta name=\"author\" content=\"國立中興大學園藝學系\">");
document.write("    <meta name=\"rating\" content=\"general\">");
document.write("    <meta name=\"robots\" content=\"all\">");
document.write("    <meta http-equiv=\"content-language\" content=\"zh-tw\">");
document.write("    <meta property=\"og:title\" content=\"國立中興大學園藝學系\">");
document.write("    <meta property=\"og:type\" content=\"website\">");
document.write("    <meta property=\"og:url\" content=\"\">");
document.write("    <meta property=\"og:image\" content=\"SRC\/images\/wejade-og.png\">");
document.write("    <meta property=\"og:description\" content=\"國立中興大學園藝學系\">");
document.write("    <link rel=\"apple-touch-icon\" href=\"SRC\/images\/apple-icon.png\">");
document.write("    <link rel=\"shortcut icon\" href=\"SRC\/images\/favicon\/favicon.ico\" type=\"image\/x-icon\">");
document.write("    <link rel=\"bookmark\" href=\"SRC\/images\/favicon\/favicon.ico\" type=\"image\/x-icon\">");
document.write("    <link href=\"https:\/\/fonts.googleapis.com\/css2?family=Amiri&display=swap\" rel=\"stylesheet\">");
document.write("    <link rel=\"stylesheet\" href=\"SRC\/font-awesome-4.7.0\/css\/font-awesome.min.css\">");
document.write("    <link href=\"SRC\/css\/_normalize.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("    <link href=\"SRC\/css\/animate.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("    ");
document.write("    <link href=\"SRC\/css\/slick.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("    <link href=\"SRC\/css\/slick-theme.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("    <link href=\"SRC\/css\/master.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("");
document.write("<\/head>");
document.write("");
document.write("<body>");
document.write("    <header>");
document.write("        <div class=\"header-menu\">");
document.write("            <div class=\"header-top-nav\">");
document.write("                <!-- 桌機logo -->");
document.write("                <div class=\"logo hide-1200\">");
document.write("                    <a href=\"index.html\"><img src=\"SRC\/images\/logo.png\"><\/a>");
document.write("                <\/div>");
document.write("                <div class=\"header-top-nav-right\">");
document.write("                    <a href=\"#\" Target=\"_blank\">興大首頁<\/a>");
document.write("                    <a href=\"#\" Target=\"_blank\">農資學院<\/a>");
document.write("                    <a href=\"\"  Target=\"_blank\">園藝試驗場<\/a>");
document.write("                    <a href=\"#\" Target=\"_blank\">圖書館<\/a>");
document.write("                    <a href=\"#\" Target=\"_blank\">國際事務<\/a>");
document.write("                    <div class=\"lang-box\">");
document.write("                        <span><i class=\"fa fa-globe\" aria-hidden=\"true\"><\/i>繁中<\/span>");
document.write("                        <div class=\"lang-box-drop\">");
document.write("                        <a href=\"\" class=\"active\">繁中<\/a>");
document.write("                        <a href=\"\">英文<\/a>          ");
document.write("                        <\/div>");
document.write("");
document.write("                    <\/div>");
document.write("                <\/div>    ");
document.write("            <\/div>");
document.write("            <nav class=\"main-nav\">");
document.write("                <a href=\"#\">訊息總覽<\/a>");
document.write("                <a href=\"#\">關於本系<\/a>");
document.write("                <a href=\"#\">本系成員<\/a>");
document.write("                <a href=\"#\">招生資訊<\/a>");
document.write("                <a href=\"#\">課程規劃<\/a>");
document.write("                <a href=\"#\">下載專區<\/a>");
document.write("                <a href=\"#\">系所友會<\/a>");
document.write("                <a href=\"#\">學術成果<\/a>");
document.write("                <a href=\"#\">出版刊物<\/a>");
document.write("                <a href=\"#\">網站連結<\/a>");
document.write("                <a href=\"#\">徵才訊息<\/a>");
document.write("            <\/nav>            ");
document.write("        <\/div>");
document.write("        <div class=\"header-mobile-menu \">");
document.write("            <!-- 手機logo -->");
document.write("            <div class=\"logo\">");
document.write("                <a href=\"index.html\"><img src=\"SRC\/images\/logo.png\"><\/a>");
document.write("            <\/div>");
document.write("            <div class=\"mobile-bar show-1200\"><span><\/span><span><\/span><span><\/span><\/div>");
document.write("        <\/div>");
document.write("");
document.write("    <\/header>");
document.write("");
document.write("");
