document.writeln("  <footer>");
document.writeln("      <div class=\'goTop-box\'>");
document.writeln("          <img src=\'SRC/images/top.svg\'>");
document.writeln("          TOP ");
document.writeln("      </div>");
document.writeln("      <div class=\'inner\'>");
document.writeln("          <div class=\'f-top\'>");
document.writeln("              <a href=\'index.html\'><img class=\'f-logo\' src=\'SRC/images/logo-w.svg\'></a>");
document.writeln("              <ul class=\'f-follow\'>");
document.writeln("                  <li><a href=\'\'><img src=\'SRC/images/linkedin.svg\'></a></li>");
document.writeln("                  <li><a href=\'\'><img src=\'SRC/images/yt-black.svg\'></a></li>");
document.writeln("              </ul>");
document.writeln("          </div>");
document.writeln("          <div class=\'f-bottom\'>");
document.writeln("              <ul>");
document.writeln("                  <li class=\'f-company\'>PAN WORLD CO., LTD. (Headquarter)</li>");
document.writeln("                  <li>1097-18 Mitsukaido Yamadamachi, Joso-shi, Ibaraki-ken, 303-0031 Japan</li>");
document.writeln("                  <li>TEL: +81-297-23-5560</li>");
document.writeln("                  <li>FAX: +81-297-23-5561</li>");
document.writeln("                  <li>E-mail: aricomx@mx5.nisiq.net</li>");
document.writeln("              </ul>");
document.writeln("              <ul>");
document.writeln("                  <li class=\'f-company\'>TPW Hong Yuan Co.,Ltd. (Factory, Taiwan)</li>");
document.writeln("                  <li>No. 28, Aly. 33, Ln. 125, Sec. 3, San Feng Rd., Hou Li, Taichung, Taiwan</li>");
document.writeln("                  <li>TEL: 886-4-25588740</li>");
document.writeln("                  <li>FAX: 886-4-25588742</li>");
document.writeln("                  <li>E-mail: webmaster@panworldpump.com</li>");
document.writeln("              </ul>");
document.writeln("              <div class=\'copyright\'>");
document.writeln("                  <a href=\'privacy.html\'>隱私權政策</a>");
document.writeln("                  © 2021 PAN WORLD All rights reserved.");
document.writeln("                  ");
document.writeln("              </div>");
document.writeln("          </div>");
document.writeln("      ");
document.writeln("      </div>");
document.writeln("");
document.writeln("  </footer>");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("<link rel=\'stylesheet\' href=\'SRC/fontawesome-free-5.15.1-web/css/all.min.css\'>");
document.writeln("");
document.writeln("<script type=\'text/javascript\' src=\'SRC/js/venobox/venobox.min.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'SRC/js/main.js\'></script>");
document.writeln("");
document.writeln("</html>");
document.writeln("");
document.writeln("");