document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width initial-scale=1.0 user-scalable=yes\'>");
document.writeln("    <title>..:: PAN WORLD ::..Magnetic Drive Pumps</title>");
document.writeln("    <meta name=\'keywords\' content=\'\'>");
document.writeln("    <meta name=\'description\' content=\'\'>");
document.writeln("    <meta name=\'author\' content=\'PAN WORLD\'>");
document.writeln("    <meta name=\'rating\' content=\'general\'>");
document.writeln("    <meta name=\'robots\' content=\'all\'>");
document.writeln("    <meta http-equiv=\'content-language\' content=\'zh-tw\'>");
document.writeln("    <meta property=\'og:title\' content=\'PAN WORLD\'>");
document.writeln("    <meta property=\'og:type\' content=\'website\'>");
document.writeln("    <meta property=\'og:url\' content=\'\'>");
document.writeln("    <meta property=\'og:image\' content=\'SRC/images/og.jpg\'>");
document.writeln("    <meta property=\'og:description\' content=\'PAN WORLD\'>");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'192x192\' href=\'SRC/images/favicon/apple-icon.png\'>");
document.writeln("    <link rel=\'shortcut icon\' href=\'SRC/images/favicon/favicon.png\' type=\'image/x-icon\'>");
document.writeln("    <link rel=\'bookmark\' href=\'SRC/images/favicon/favicon.png\' type=\'image/x-icon\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'SRC/css/plugin.css\'>");
document.writeln("    <link href=\'SRC/css/master.css\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("    <script type=\'text/javascript\' src=\'SRC/js/jquery-3.6.0.min.js\'></script>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("<header>");
document.writeln("");
document.writeln("    <a href=\'index.html\' class=\'logo\'><img src=\'SRC/images/logo.svg\'></a>");
document.writeln("    <nav class=\'menu-nav\'>");
document.writeln("        <div class=\'nav-a\'>");
document.writeln("            <a href=\'about.html\'>About</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-a has-drop\'>");
document.writeln("            <a href=\'product.html\'>Products</a>");
document.writeln("            <div class=\'nav-drop\'>");
document.writeln("                <div class=\'sub-drop\'>");
document.writeln("                   <a href=\'product2.html\'>General Pump</a>");
document.writeln("                   <div class=\'drop-class\'>");
document.writeln("                        <a href=\'product2.html\'>PI-Z-D Series</a>");
document.writeln("                        <a href=\'product2.html\'>PX Series</a>");
document.writeln("                        <a href=\'product2.html\'>PX-F Series</a>");
document.writeln("                        <a href=\'product2.html\'>PX-N Series</a>");
document.writeln("                        <a href=\'product2.html\'>PX-D Series</a>");
document.writeln("                        <a href=\'product2.html\'>PX-D-F Series</a>");
document.writeln("                        <a href=\'product2.html\'>PX-D-N Series</a>");
document.writeln("                        <a href=\'product2.html\'>PS Series</a>");
document.writeln("                        <a href=\'product2.html\'>PS-F Series</a>");
document.writeln("                        <a href=\'product2.html\'>PS-K Series</a>");
document.writeln("                        <a href=\'product2.html\'>PW Series</a>");
document.writeln("                        <a href=\'product2.html\'>PW-F Series</a>");
document.writeln("                        <a href=\'product2.html\'>PW-K Series</a>");
document.writeln("                        <a href=\'product2.html\'>PWE Series</a>");
document.writeln("                        <a href=\'product2.html\'>PWE-F Series</a>");
document.writeln("                   </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'sub-drop\'>");
document.writeln("                    <a href=\'product2.html\'>Engineering Pump</a>");
document.writeln("                    <div class=\'drop-class\'>");
document.writeln("                        <a href=\'product2.html\'>PX-SP Series</a>");
document.writeln("                        <a href=\'product2.html\'>PS-SP Series</a>");
document.writeln("                        <a href=\'product2.html\'>PW-SP Series</a>");
document.writeln("                        <a href=\'product2.html\'>PS-N Series</a>");
document.writeln("                        <a href=\'product2.html\'>PS-N-K Series</a>");
document.writeln("                        <a href=\'product2.html\'>PW-N Series</a>");
document.writeln("                        <a href=\'product2.html\'>PW-N-K Series</a>");
document.writeln("                        <a href=\'product2.html\'>PW-C Series</a>");
document.writeln("                        <a href=\'product2.html\'>PWX-C Series</a>");
document.writeln("                        <a href=\'product2.html\'>PW-XJ Series</a>");
document.writeln("                        <a href=\'product2.html\'>PWH Series</a>");
document.writeln("                        <a href=\'product2.html\'>PWH-F Series</a>");
document.writeln("                        <a href=\'product2.html\'>PV Series</a>");
document.writeln("                        <a href=\'product2.html\'>PG Series</a>");
document.writeln("                        <a href=\'product2.html\'>PW-V Series</a>");
document.writeln("                        <a href=\'product2.html\'>PA Series</a>");
document.writeln("                        <a href=\'product2.html\'>PA-S Series</a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'sub-drop\'>");
document.writeln("                    <a href=\'product2.html\'>High Tech. Pump</a>");
document.writeln("                    <div class=\'drop-class\'>");
document.writeln("                        <a href=\'product2.html\'>PH  Series</a>");
document.writeln("                        <a href=\'product2.html\'>PM  Series</a>  ");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                ");
document.writeln("            </div> ");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-a\'>");
document.writeln("            <a href=\'price.html\'>Real offer & Price </a>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-a has-drop\'>");
document.writeln("            <a href=\'app.html\'>Application</a> ");
document.writeln("            <div class=\'nav-drop\'>");
document.writeln("                <a href=\'app.html\'>Heat Transfer</a>");
document.writeln("                <a href=\'app.html\'>Semi - Conductor</a>");
document.writeln("                <a href=\'app.html\'>Scrubher</a>");
document.writeln("                <a href=\'app.html\'>Fuel Cell</a>");
document.writeln("                <a href=\'app.html\'>Pharmaceutical</a>");
document.writeln("                <a href=\'app.html\'>Chemical , Electricostatic Plating</a>");
document.writeln("                <a href=\'app.html\'>Chemical Processing</a>");
document.writeln("                <a href=\'app.html\'>Surface Treatment (PCB Equipent)</a>");
document.writeln("                <a href=\'app.html\'>Surface Treatment (Etching Equipment)</a>");
document.writeln("                <a href=\'app.html\'>Food Processing 1</a>");
document.writeln("                <a href=\'app.html\'>Food Processing 2</a>");
document.writeln("                <a href=\'app.html\'>Food Processing 3</a>");
document.writeln("            </div>            ");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-a  has-drop\'>");
document.writeln("            <a href=\'download.html\'>Download</a>");
document.writeln("            <div class=\'nav-drop\'>");
document.writeln("                <a href=\'download.html\'>Catalog / DIM & WT</a>");
document.writeln("                <a href=\'download.html\'>Technical Data</a>");
document.writeln("            </div>     ");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-a  has-drop\'>");
document.writeln("            <a href=\'contact.html\'>Contact</a>");
document.writeln("            <div class=\'nav-drop\'>");
document.writeln("                <a href=\'contact.html\'>Contact Information</a>");
document.writeln("                <a href=\'contact2.html\'>Inquiry Form</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </nav>");
document.writeln("    <div class=\'header-right\'>");
document.writeln("        <div  class=\'header-search\'>");
document.writeln("            <i class=\'fas fa-search\'></i>");
document.writeln("            <div class=\'search-drop\'>");
document.writeln("                <form method=\'post\' action=\'search.html\'>");
document.writeln("                    <input type=\'text\' placeholder=\'Search\'>");
document.writeln("                </form>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'header-lang\'>");
document.writeln("            <!-- 顯示當前語系 -->");
document.writeln("            EN");
document.writeln("            <!-- 顯示當前語系 END-->");
document.writeln("            <div class=\'lang-drop\'>");
document.writeln("                <a href=\'\' class=\'active\'>TW</a>");
document.writeln("                <a href=\'\'>JP</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-bar show-1200\' >");
document.writeln("            <span></span>");
document.writeln("            <span></span>");
document.writeln("            <span></span>");
document.writeln("        </div>        ");
document.writeln("    </div>");
document.writeln("");
document.writeln("</header>");
document.writeln("<div class=\'mask-bg\'></div>");
document.writeln("");