document.write("<footer>");
document.write("    <div class=\"footer_contBox\">");
document.write("        <div class=\"footer_left-box\">");
document.write("            <div class=\"Ft-Lt-Fs01\">");
document.write("                <div class=\"Ft-Lt-Fs01TT\"><a href=\"product_list.html\">JS系列<\/a><\/div>");
document.write("                <ul>");
document.write("                    <li><a href=\"product_detailed.html\">包裝自動化設備<\/a><\/li>");
document.write("                    <li><a href=\"product_detailed.html\">包裝自動化設備<\/a><\/li>");
document.write("                    <li><a href=\"product_detailed.html\">包裝自動化設備<\/a><\/li>");
document.write("                    <li><a href=\"product_detailed.html\">產品名稱<\/a><\/li>");
document.write("                <\/ul>");
document.write("            <\/div>");
document.write("            <div class=\"Ft-Lt-Fs02\">");
document.write("                <div class=\"Ft-Lt-Fs02TT\"><a href=\"product_list.html\">JL系列<\/a><\/div>");
document.write("                <ul>");
document.write("                    <li><a href=\"product_detailed.html\">包裝自動化設備<\/a><\/li>");
document.write("                    <li><a href=\"product_detailed.html\">產品名稱<\/a><\/li>");
document.write("                <\/ul>");
document.write("            <\/div>");
document.write("            <div class=\"Ft-Lt-Fs03\">");
document.write("                <div class=\"Ft-Lt-Fs03TT\"><a href=\"product_list.html\">JA系列<\/a><\/div>");
document.write("                <ul>");
document.write("                    <li><a href=\"product_detailed.html\">產品名稱<\/a><\/li>");
document.write("                    <li><a href=\"product_detailed.html\">產品名稱<\/a><\/li>");
document.write("                <\/ul>");
document.write("            <\/div>");
document.write("            <div class=\"Ft-Lt-Fs04\">");
document.write("                <div class=\"Ft-Lt-Fs03TT\"><a href=\"product_list.html\">JBS系列<\/a><\/div>");
document.write("                <ul>");
document.write("                    <li><a href=\"product_detailed.html\">產品名稱<\/a><\/li>");
document.write("                    <li><a href=\"product_detailed.html\">產品名稱<\/a><\/li>");
document.write("                <\/ul>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("        <div class=\"footer_right-box\">");
document.write("            <div class=\"Ft_Rt-box\">");
document.write("                <a href=\"about.html\"><span>關於捷羚<\/span><\/a>");
document.write("                <a href=\"product.html\"><span>產品資訊<\/span><\/a>");
document.write("                <a href=\"news_list.html\"><span>最新消息<\/span><\/a>");
document.write("                <a href=\"download.html\"><span>檔案下載<\/span><\/a>");
document.write("                <a href=\"faq.html\"><span>常見問題<\/span><\/a>");
document.write("                <a href=\"video.html\"><span>影音專區<\/span><\/a>");
document.write("                <a href=\"contact.html\"><span>洽詢表單<\/span><\/a>");
document.write("            <\/div>");
document.write("            <div class=\"Ft_Rt_search\">");
document.write("                <form action=\"search.html\" class=\"Ft_Rt_search_bbox\">");
document.write("                    <input type=\"search\" placeholder=\"產品搜尋\" >");
document.write("                <\/form>");
document.write("                <ul class=\"Ft_Rt_search_FBIC\"><img src=\"images\/FB_ic.svg\" alt=\"\"><\/ul>");
document.write("                ");
document.write("            <\/div>");
document.write("            <div class=\"Copyright-box\">Copyright©2021 捷羚機械有限公司 All Rights Reserved.<\/div>");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("    <div class=\"footer-leftBg\"><\/div>");
document.write("    <div class=\"footer-ReftBg\"><\/div>");
document.write("<\/footer>");
document.write("<script type=\"text\/javascript\" src=\"js\/main.js\"><\/script>");
document.write("<\/body>");
document.write("<\/html>");
