document.write("<!DOCTYPE html>");
document.write("<html lang=\"zh-Hant-TW\">");
document.write("  <head>");
document.write("    <meta charset=\"UTF-8\"\/>");
document.write("    <meta name=\"viewport\" content=\"width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=yes\" \/>");
document.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">");
document.write("    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">");
document.write("    <title>捷羚機械有限公司<\/title>");
document.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"images\/apple-icon-180x180.png\">");
document.write("    <link rel=\"icon\" type=\"image\/png\" sizes=\"192x192\"  href=\"images\/android-icon-192x192.png\">");
document.write("    <link rel=\"icon\" type=\"image\/png\" sizes=\"32x32\" href=\"images\/favicon-32x32.png\">");
document.write("    <link rel=\"manifest\" href=\"images\/manifest.json\">");
document.write("    <meta name=\"msapplication-TileColor\" content=\"#ffffff\">");
document.write("    <meta name=\"msapplication-TileImage\" content=\"images\/ms-icon-144x144.png\">");
document.write("    <meta name=\"theme-color\" content=\"#ffffff\">");
document.write("    <link rel=\"shortcut icon\" href=\"images\/favicon\/favicon.png\" type=\"image\/x-icon\">");
document.write("    <link rel=\"icon\" href=\"images\/favicon\/favicon.png\" type=\"image\/x-icon\">");
document.write("    <link rel=\"stylesheet\" href=\"fontawesome-free-5.15.1-web\/css\/all.min.css\">");
document.write("    <link rel=\"stylesheet\" type=\"text\/css\" href=\"css\/master.css\"\/>");
document.write("");
document.write("    <script type=\"text\/javascript\" src=\"js\/jquery-3.1.1.js\"><\/script>");
document.write("  <\/head>");
document.write("  <body>");
document.write("    <header>");
document.write("      <div class=\"header_box\">");
document.write("        <div class=\"logo_box\"><a href=\"index.html\"><img src=\"images\/logo.svg\" alt=\"\"><\/a><\/div>");
document.write("        <nav>");
document.write("            <a href=\"about.html\"><span>關於捷羚<\/span><\/a>");
document.write("            <a href=\"product.html\"><span>產品資訊<\/span><\/a>");
document.write("            <a href=\"news_list.html\"><span>最新消息<\/span><\/a>");
document.write("            <a href=\"download.html\"><span>檔案下載<\/span><\/a>");
document.write("            <a href=\"faq.html\"><span>常見問題<\/span><\/a>");
document.write("            <a href=\"video.html\"><span>影音專區<\/span><\/a>");
document.write("            <a href=\"contact.html\"><span>聯絡資訊<\/span><\/a>");
document.write("            <ul class=\"language\">");
document.write("                <span>繁體中文<\/span>");
document.write("                <ul>");
document.write("                    <li><a href=\"javascript: void(0)\">English<\/a><\/li>");
document.write("                    <li><a href=\"javascript: void(0)\">Japanese<\/a><\/li>");
document.write("                <\/ul>    ");
document.write("            <\/ul>");
document.write("          <\/nav>");
document.write("      <\/div>");
document.write("    <\/header>");
document.write("    <div class=\"mobile_menu\"><img src=\"images\/Mobile_menu.svg\" alt=\"\"><\/div>");
document.write("    <div class=\"mobile_menu_Allbox\">");
document.write("        <div class=\"mobile_menu_box\">");
document.write("            <div class=\"mobile_menu_boxBT_allbox\">");
document.write("                <a href=\"about.html\"><ul class=\"mobile_menu_boxBT\">關於捷羚<\/ul><\/a>");
document.write("                <a href=\"product.html\"><ul class=\"mobile_menu_boxBT\">產品資訊<\/ul><\/a>");
document.write("                <a href=\"news_list.html\"><ul class=\"mobile_menu_boxBT\">最新消息<\/ul><\/a>");
document.write("                <a href=\"download.html\"><ul class=\"mobile_menu_boxBT\">檔案下載<\/ul><\/a>");
document.write("                <a href=\"faq.html\"><ul class=\"mobile_menu_boxBT\">常見問題<\/ul><\/a>");
document.write("                <a href=\"video.html\"><ul class=\"mobile_menu_boxBT\">影音專區<\/ul><\/a>");
document.write("                <a href=\"contact.html\"><ul class=\"mobile_menu_boxBT\">聯絡資訊<\/ul><\/a>");
document.write("                <div class=\"mobile_lang\">");
document.write("                    <a href=\"javascript: void(0)\">English<\/a>");
document.write("                    <a href=\"javascript: void(0)\">Japanese<\/a>                    ");
document.write("                <\/div>");
document.write("");
document.write("            <\/div>  ");
document.write("        <\/div>");
document.write("    <\/div>");
document.write("<script>");
document.write("    $('.mobile_menu').click(function(){");
document.write("        $('.mobile_menu_box').toggleClass(\"open\");");
document.write("    });");
document.write("<\/script>");
