document.writeln("<ul class=\"left-column-nav\">");
document.writeln("    <div class=\"member-admin-left\">");
document.writeln("        <!-- 一般 .general-->");
document.writeln("        <!-- <div class=\"member-admin-pic general\"><img src=\"SRC/images/girl.svg\"></div> -->");
document.writeln("");
document.writeln("");
document.writeln("        <!-- 黃金 .gold / 照片-->");
document.writeln("        <!-- <div class=\"member-admin-pic gold\"><img src=\"SRC/images/girl.svg\"></div> -->");
document.writeln("");
document.writeln("        <!-- 白金 .platinum  -->");
document.writeln("        <div class=\"member-admin-pic platinum\"><img src=\"SRC/images/boy.svg\"></div>");
document.writeln("");
document.writeln("        <!-- 鑽石 .diamond / 預設男性頭像 -->");
document.writeln("        <!-- <div class=\"member-admin-pic diamond\"><img src=\"SRC/images/boy.svg\"></div> -->");
document.writeln("");
document.writeln("        <!-- 慈善大使 .color / 預設女性頭像-->");
document.writeln("        <!-- <div class=\"member-admin-pic color\"><img src=\"SRC/images/girl.svg\"></div> -->");
document.writeln("");
document.writeln("        <div class=\"member-admin-name\">歡迎，樂先生</div>");
document.writeln("        <div class=\"member-left-level\"><span>會員等級</span>白金會員</div>");
document.writeln("        <div class=\"member-left-level\"><span>目前積分</span>20000</div>");
document.writeln("    </div>");
document.writeln("    <li class=\"title\">會員專區</li>");
document.writeln("    <li><a href=\"member.html\">會員首頁</a></li>");
document.writeln("    <li><a href=\"member_level.html\">會員等級說明</a></li>");
document.writeln("    <li><a href=\"member_history.html\">歷史訂單</a></li>");
document.writeln("    <li><a href=\"member_modify.html\">會員資料修改</a></li>");
document.writeln("    <li><a href=\"index.html\">登出</a></li>");
document.writeln("</ul>");