document.writeln('<div class="lightbox ask-open form-style">');
document.writeln('    <div class="lightbox-content">');
document.writeln('        <img class="lightbox-close" src="SRC/images/close.svg">');
document.writeln('        <div class="lightbox-scroll">');
document.writeln('            <form action="member_history.html">');
document.writeln('                <div class="lightbox-title">訂單詢問</div>');
document.writeln('                <div class="lightbox-name"><span>訂單編號</span>20182723410</div>');
document.writeln('                <div class="lightbox-name"><span>姓名</span>樂先生</div>');
document.writeln('                <div class="input-row">');
document.writeln('                    <input type="email" name="email">');
document.writeln('                    <label>Email帳號</label>            ');
document.writeln('                </div>           ');
document.writeln('                <div class="input-row">');
document.writeln('                    <input onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')">');
document.writeln('                    <label>聯絡電話</label>');
document.writeln('                </div>');
document.writeln('                <div class="input-row form-textarea"> ');
document.writeln('                    <textarea></textarea>');
document.writeln('                    <label class="form-title">詢問內容</label>');
document.writeln('                </div>');
document.writeln('                <div class="step-btn">');
document.writeln('                    <button type="reset">重新填寫</button>');
document.writeln('                    <button type="submit">送出詢問</button>');
document.writeln('                </div>           ');
document.writeln('            </form>            ');
document.writeln('        </div>');
document.writeln('          ');
document.writeln('    </div>');
document.writeln('  ');
document.writeln('</div>');
