document.writeln('    <div class="other-buy">');
document.writeln('        <div class="price">$500<span>最多人購買</span></div>');
document.writeln('        <img src="SRC/images/demo/prod-r.jpg">');
document.writeln('        <div class="other-buy-content">');
document.writeln('            <div class="other-buy-title">遠方希望</div>');
document.writeln('            <div class="other-buy-name">創作者：鐘美梅</div>');
document.writeln('            <div class="other-buy-text">');
document.writeln('                1960年生<br>');
document.writeln('                ◎脊髓損傷者<br>');
document.writeln('                2020年<br>');
document.writeln('                -榮獲台中市政府「妳好棒！韌力女性」<br>');
document.writeln('                -出版自傳繪本《媽媽嫁妝》<br>');
document.writeln('                -榮獲第22屆全球熱愛生命獎章<br>');
document.writeln('            </div>');
document.writeln('            <a href="products_detail.html">支持創作者</a>                    ');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('    <div class="other-buy">');
document.writeln('        <div class="price">$500<span>最多人購買</span></div>');
document.writeln('        <img src="SRC/images/demo/pr4.jpg">');
document.writeln('        <div class="other-buy-content">');
document.writeln('            <div class="other-buy-title">遠方希望</div>');
document.writeln('            <div class="other-buy-name">創作者：鐘美梅</div>');
document.writeln('            <div class="other-buy-text">');
document.writeln('                1960年生<br>');
document.writeln('                ◎脊髓損傷者<br>');
document.writeln('                2020年<br>');
document.writeln('                -榮獲台中市政府「妳好棒！韌力女性」<br>');
document.writeln('                -出版自傳繪本《媽媽嫁妝》<br>');
document.writeln('                -榮獲第22屆全球熱愛生命獎章<br>');
document.writeln('            </div>');
document.writeln('            <a href="products_detail.html">支持創作者</a>                    ');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('    <div class="other-buy">');
document.writeln('        <div class="price">$500</div>');
document.writeln('        <img src="SRC/images/demo/pr4-2.jpg">');
document.writeln('        <div class="other-buy-content">');
document.writeln('            <div class="other-buy-title">遠方希望</div>');
document.writeln('            <div class="other-buy-name">創作者：鐘美梅</div>');
document.writeln('            <div class="other-buy-text">');
document.writeln('                1960年生<br>');
document.writeln('                ◎脊髓損傷者<br>');
document.writeln('                2020年<br>');
document.writeln('                -榮獲台中市政府「妳好棒！韌力女性」<br>');
document.writeln('                -出版自傳繪本《媽媽嫁妝》<br>');
document.writeln('                -榮獲第22屆全球熱愛生命獎章<br>');
document.writeln('            </div>');
document.writeln('            <a href="products_detail.html">支持創作者</a>                    ');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('    <div class="other-buy">');
document.writeln('        <div class="price">$500<span>最多人購買</span></div>');
document.writeln('        <img src="SRC/images/demo/pr4-2.jpg">');
document.writeln('        <div class="other-buy-content">');
document.writeln('            <div class="other-buy-title">遠方希望</div>');
document.writeln('            <div class="other-buy-name">創作者：鐘美梅</div>');
document.writeln('            <div class="other-buy-text">');
document.writeln('                1960年生<br>');
document.writeln('                ◎脊髓損傷者<br>');
document.writeln('                2020年<br>');
document.writeln('                -榮獲台中市政府「妳好棒！韌力女性」<br>');
document.writeln('                -出版自傳繪本《媽媽嫁妝》<br>');
document.writeln('                -榮獲第22屆全球熱愛生命獎章<br>');
document.writeln('            </div>');
document.writeln('            <a href="products_detail.html">支持創作者</a>                    ');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('    <div class="other-buy">');
document.writeln('        <div class="price">$500</div>');
document.writeln('        <img src="SRC/images/demo/pr4.jpg">');
document.writeln('        <div class="other-buy-content">');
document.writeln('            <div class="other-buy-title">遠方希望</div>');
document.writeln('            <div class="other-buy-name">創作者：鐘美梅</div>');
document.writeln('            <div class="other-buy-text">');
document.writeln('                1960年生<br>');
document.writeln('                ◎脊髓損傷者<br>');
document.writeln('                2020年<br>');
document.writeln('                -榮獲台中市政府「妳好棒！韌力女性」<br>');
document.writeln('                -出版自傳繪本《媽媽嫁妝》<br>');
document.writeln('                -榮獲第22屆全球熱愛生命獎章<br>');
document.writeln('            </div>');
document.writeln('            <a href="products_detail.html">支持創作者</a>                    ');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('    <div class="other-buy">');
document.writeln('        <div class="price row j-s a-c">$500<span>最多人購買</span></div>');
document.writeln('        <img src="SRC/images/demo/prod-r.jpg">');
document.writeln('        <div class="other-buy-content">');
document.writeln('            <div class="other-buy-title">遠方希望</div>');
document.writeln('            <div class="other-buy-name">創作者：鐘美梅</div>');
document.writeln('            <div class="other-buy-text">');
document.writeln('                1960年生<br>');
document.writeln('                ◎脊髓損傷者<br>');
document.writeln('                2020年<br>');
document.writeln('                -榮獲台中市政府「妳好棒！韌力女性」<br>');
document.writeln('                -出版自傳繪本《媽媽嫁妝》<br>');
document.writeln('                -榮獲第22屆全球熱愛生命獎章<br>');
document.writeln('            </div>');
document.writeln('            <a href="products_detail.html">支持創作者</a>                    ');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('    <div class="other-buy">');
document.writeln('        <div class="price">$500</div>');
document.writeln('        <img src="SRC/images/demo/pr4.jpg">');
document.writeln('        <div class="other-buy-content">');
document.writeln('            <div class="other-buy-title">遠方希望</div>');
document.writeln('            <div class="other-buy-name">創作者：鐘美梅</div>');
document.writeln('            <div class="other-buy-text">');
document.writeln('                1960年生<br>');
document.writeln('                ◎脊髓損傷者<br>');
document.writeln('                2020年<br>');
document.writeln('                -榮獲台中市政府「妳好棒！韌力女性」<br>');
document.writeln('                -出版自傳繪本《媽媽嫁妝》<br>');
document.writeln('                -榮獲第22屆全球熱愛生命獎章<br>');
document.writeln('            </div>');
document.writeln('            <a href="products_detail.html">支持創作者</a>                    ');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('    <div class="other-buy">');
document.writeln('        <div class="price row j-s a-c">$500<span>最多人購買</span></div>');
document.writeln('        <img src="SRC/images/demo/prod-r.jpg">');
document.writeln('        <div class="other-buy-content">');
document.writeln('            <div class="other-buy-title">遠方希望</div>');
document.writeln('            <div class="other-buy-name">創作者：鐘美梅</div>');
document.writeln('            <div class="other-buy-text">');
document.writeln('                1960年生<br>');
document.writeln('                ◎脊髓損傷者<br>');
document.writeln('                2020年<br>');
document.writeln('                -榮獲台中市政府「妳好棒！韌力女性」<br>');
document.writeln('                -出版自傳繪本《媽媽嫁妝》<br>');
document.writeln('                -榮獲第22屆全球熱愛生命獎章<br>');
document.writeln('            </div>');
document.writeln('            <a href="products_detail.html">支持創作者</a>                    ');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('');
