document.writeln('    <div class="full">');
document.writeln('        <nav class="bread"><a href="index.html">Home</a><span class="bread-space">/</span>探險</nav>');
document.writeln('        <div class="prod-left">');
document.writeln('            <div class="prod-gallery">');
document.writeln('                <!-- 影片 -->');
document.writeln('                <div class="prod-video gallery-i">');
document.writeln('                    <input type="button">');
document.writeln('                    <div class="video-pic" style="background-image: url(SRC/images/demo/pr2.jpg) ;"></div>');
document.writeln('                    <video id="video_paly"  controls><source src="SRC/images/demo/video2.mp4" type="video/mp4">');
document.writeln('                </div> ');
// document.writeln('                <div class="prod-video gallery-i embed-container">');
// document.writeln('                    <iframe src="https://www.youtube.com/embed/PpAmoHtr0ow" frameborder="0" allowfullscreen=""></iframe>');
// document.writeln('                </div>');
document.writeln('                <!-- 影片 end-->');
document.writeln('                <div class="gallery-i">');
document.writeln('                    <img src="SRC/images/demo/pr1.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-i">');
document.writeln('                    <img src="SRC/images/demo/pr2.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-i">');
document.writeln('                    <img src="SRC/images/demo/pr1.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-i">');
document.writeln('                    <img src="SRC/images/demo/pr2.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-i">');
document.writeln('                    <img src="SRC/images/demo/pr1.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-i">');
document.writeln('                    <img src="SRC/images/demo/pr2.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-i">');
document.writeln('                    <img src="SRC/images/demo/pr1.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-i">');
document.writeln('                    <img src="SRC/images/demo/pr2.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-i">');
document.writeln('                    <img src="SRC/images/demo/pr1.jpg">');
document.writeln('                </div>');
document.writeln('            </div>');
document.writeln('            <div class="prod-gallery-nav">');
document.writeln('                <!-- 對應影片 -->');
document.writeln('                <div class="gallery-item active">');
document.writeln('                    <img src="SRC/images/demo/pr2.jpg">');
document.writeln('                    <div class="play-nav"><img src="SRC/images/play-nav.svg"></div>');
document.writeln('                </div>');
document.writeln('                <!-- 對應影片 end-->');
document.writeln('                <div class="gallery-item">');
document.writeln('                    <img src="SRC/images/demo/pr1.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-item">');
document.writeln('                    <img src="SRC/images/demo/pr2.jpg">');
document.writeln('                </div>');
document.writeln('');
document.writeln('                <div class="gallery-item">');
document.writeln('                    <img src="SRC/images/demo/pr1.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-item">');
document.writeln('                    <img src="SRC/images/demo/pr2.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-item">');
document.writeln('                    <img src="SRC/images/demo/pr1.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-item">');
document.writeln('                    <img src="SRC/images/demo/pr2.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-item">');
document.writeln('                    <img src="SRC/images/demo/pr1.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-item">');
document.writeln('                    <img src="SRC/images/demo/pr2.jpg">');
document.writeln('                </div>');
document.writeln('                <div class="gallery-item">');
document.writeln('                    <img src="SRC/images/demo/pr1.jpg">');
document.writeln('                </div>');
document.writeln('            </div>');
document.writeln('        </div>');
document.writeln('        <div class="prod-right">');
document.writeln('            <div class="new-arrival">最新上架</div>');
document.writeln('            <div class="prod-title">小光點畫廊</div>');
document.writeln('            <div class="support"><img src="SRC/images/happy.svg">已有<span class="red">10,695人</span>支持專案，<span>我們的目標是：18,200人</span></div>');
document.writeln('            <div class="progress">');
document.writeln('                <div class="progress-bar" style="width: 45%"></div>');
document.writeln('            </div>');
document.writeln('            <div class="user_editor">');
document.writeln('                <div class="font20"><strong>破碎恐懼，拾起勇敢</strong> </div>');
document.writeln('                <p>Mian Liu － 恰克-馬利-杜斯氏症</p>');
document.writeln('                <p>– 孩子與我一起吧！<br>– 百合花</p>');
document.writeln('                <p style="color: #757575;font-size: 14px;">身心障礙者的作品需要被更多人看見，更需要您的鼓勵與肯定，您的購畫能為他們開啟一道扭轉人生的大門，因為您的支持讓他們看見希望！</p>');
document.writeln('            </div>');
document.writeln('            <div class="dream">');
document.writeln('                <span class="step"><img src="SRC/images/step1.svg">選擇夢想</span><img class="h17" src="SRC/images/more.svg">');
document.writeln('                <span class="step"><img src="SRC/images/step2.svg">進行捐款</span><img class="h17" src="SRC/images/more.svg">');
document.writeln('                <span class="step"><img src="SRC/images/step3.svg">回饋社會</span>');
document.writeln('            </div>');
document.writeln('            <div class="time-text">');
document.writeln('                <span>剩餘時間</span>72 天');
document.writeln('            </div>');
document.writeln('            <div class="time-text"><span>時程</span>2020/09/02 20:00 – 2020/10/28 02:00</div>');
document.writeln('            <div class="donate">');
document.writeln('                <!-- <div class="title">選擇支持金額</div> -->');
document.writeln('                <div class="donate-list">');
document.writeln('                    <!-- 一個選項, 選擇加.focus -->');
document.writeln('                    <div class="donate-item focus">');
document.writeln('                        <div class="tip">最多人購買</div>');
document.writeln('                        <div class="price">NT$<span>300</span></div>');
document.writeln('                    </div>');
document.writeln('                    <!-- 一個選項 END -->');
document.writeln('                    <div class="donate-item">');
document.writeln('                        <div class="tip">最多人購買</div>');
document.writeln('                        <div class="price">NT$<span>600</span></div>');
document.writeln('                    </div>');
document.writeln('                    <div class="donate-item">');
document.writeln('                        <div class="tip">最多人購買</div>');
document.writeln('                        <div class="price">NT$<span>900</span></div>');
document.writeln('                    </div>');
document.writeln('                    <div class="donate-item">');
document.writeln('                        <div class="tip">最多人購買</div>');
document.writeln('                        <div class="price">NT$<span>1200</span></div>');
document.writeln('                    </div>                 ');
document.writeln('                </div>');
document.writeln('');
document.writeln('                <div class="donate-btn">');
document.writeln('                    <div class="btn"><a href="">立即購買</a></div>');
document.writeln('                    <div class="btn">加入夢想清單</div>');
document.writeln('                </div>');
document.writeln('            </div>');
document.writeln('            <ul class="share-list">分享');
document.writeln('                <li><a href=""><img src="SRC/images/facebook.svg"></a></li>');
document.writeln('                <li><a href=""><img src="SRC/images/s-ig.svg"></a></li>');
document.writeln('                <li><a href=""><img src="SRC/images/line.svg"></a> </li>');
document.writeln('            </ul>');
document.writeln('            <img class="logo-pic" src="SRC/images/demo/logo-pic2.jpg">');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('');
document.writeln('    <div class="m-fixed-cart show-1200">');
document.writeln('        <img src="SRC/images/gift.svg">立即購買');
document.writeln('    </div>');
document.writeln('    <div class="m-cart-mask"></div>');
