document.writeln("	");
document.writeln("	<footer>");
document.writeln("		<div class=\"inner\">");
document.writeln("			<ul class=\"footer-follow\">");
document.writeln("				<span>關注我們</span>");
document.writeln("				<li><a href=\"https://www.facebook.com/letschange.cc\" target=\"_blank\"><img src=\"SRC/images/fb.svg\"></a></li>");
document.writeln("				<li><a href=\"https://www.instagram.com/letschange.cc/\" target=\"_blank\"><img src=\"SRC/images/ig.svg\"></a></li>");
document.writeln("				<li><a href=\"https://line.me/R/ti/p/%40242agiht\" class=\"line_g\" target=\"_blank\"><img src=\"SRC/images/line_g.svg\"></a></li>");
document.writeln("				<li><a href=\"https://www.youtube.com\" target=\"_blank\"><img src=\"SRC/images/youtube.svg\"></a></li>");
document.writeln("			</ul>");
document.writeln("			<div class=\"footer-contact\"><span>有什麼問題嗎?</span>聯絡信箱<a href=\"mailto:weloveyou@letschange.cc\">weloveyou@letschange.cc</a></div>");
document.writeln("			<ul class=\"footer-nav j-s\">");
document.writeln("				<li><a href=\"item.html\">項目介紹</a></li>");
document.writeln("				<li><a href=\"about.html\">關於我們</a></li>");
document.writeln("				<li><a href=\"blog.html\">最新消息</a></li>");
document.writeln("				<li><a href=\"trademark.html\">商標資源</a></li>");
document.writeln("				<li><a href=\"question.html\">常見問題</a></li>");
document.writeln("				<li><a href=\"winners.html\">贏家</a></li>");
document.writeln("				<li><a href=\"blog.html\">部落格</a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("		<div class=\"footer-bottom inner\">");
document.writeln("			<div class=\"copyright\">");
document.writeln("				<a href=\"index.html\"><img src=\"SRC/images/footer-logo.svg\"></a>");
document.writeln("				<div class=\"copyright-text\"><span>© 2020 Gigatek Inc. ALL RIGHTS RESERVED.</div>");
document.writeln("			</div>");
document.writeln("			<ul class=\"footer-bottom-nav\">");
document.writeln("				<li><a href=\"statement.html\">平台聲明</a></li>");
document.writeln("				<li><a href=\"rules.html\">平台規則</a></li>");
document.writeln("				<li><a href=\"job.html\">職業說明</a></li>");
document.writeln("				<li><a href=\"law.html\">台灣法規</a></li>");
document.writeln("				<li><a href=\"terms.html\">使用條款</a></li>");
document.writeln("				<li><a href=\"privacy.html\">隱私權政策</a></li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</footer>");
document.writeln("    <!--== all js ==-->");
document.writeln("    <script type=\"text/javascript\" src=\"SRC/js/1.12.4_jquery.min.js\"></script>");
document.writeln("    <script type=\"text/javascript\" src=\"SRC/js/slick.min.js\"></script> ");
document.writeln("    <script type=\"text/javascript\" src=\"SRC/js/venobox/venobox.min.js\"></script>");
document.writeln("    <script src=\"SRC/js/jquery.validate.min.js\"></script>");
document.writeln("    <script type=\"text/javascript\" src=\"SRC/js/jquery.twzipcode.min.js\"></script>");
document.writeln("    <script type=\"text/javascript\" src=\"SRC/js/main.js\"></script>");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("</html>");