document.write("<!doctype html>");
document.write("<html>");
document.write("<head>");
document.write("    <meta charset=\"utf-8\">");
document.write("    <meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\">");
document.write("    <meta name=\"viewport\" content=\"width=device-width initial-scale=1.0 user-scalable=yes\">");
document.write("    <meta name=\"format-detection\" content=\"telephone=no\">");
document.write("    <title>樂趣捐 Lets Change<\/title>");
document.write("    <!--[if IE]>");
document.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">``");
document.write("    <![endif]-->");
document.write("    <link rel=\"apple-touch-icon\" href=\"SRC\/images\/Lets-Change.png\">");
document.write("    <link rel=\"shortcut icon\" href=\"SRC\/images\/favicon\/favicon.ico\" type=\"image\/x-icon\">");
document.write("    <link rel=\"bookmark\" href=\"SRC\/images\/favicon\/favicon.ico\" type=\"image\/x-icon\">");

document.write("    <meta name=\"Robots\" content=\"All\">");
document.write("    <meta http-equiv=\"content-language\" content=\"zh-tw\">");
document.write("    <!-- og -->");

document.write("    <meta property=\"og:type\" content=\"website\">");
document.write("    <meta property=\"og:image\" content=\"SRC\/images\/og.jpg\">");
document.write("    <meta property=\"og:url\" content=\"\">");
document.write("    <link rel=\"stylesheet\" href=\"SRC\/fontawesome-free-5.15.1-web\/css\/all.min.css\">");
document.write("    <link href=\"SRC\/css\/_normalize.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("    <link href=\"SRC\/css\/animate.css\" rel=\"stylesheet\" type=\"text\/css\">  ");
document.write("    <link href=\"SRC\/css\/slick.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("    <link href=\"SRC\/css\/slick-theme.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("    <link href=\"SRC\/js\/venobox\/venobox.min.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("    <link href=\"SRC\/css\/master.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("");
document.write("<\/head>");
document.write("");
document.write("<body >");
document.write("	<header>");
document.write("        <div class=\"inner\">");
document.write("            <div class=\"logo\"><a href=\"index.html\"><img src=\"SRC\/images\/logo.svg\"><\/a><\/div>");
document.write("            ");
document.write("            <div class=\"header-nav\">");
document.write("                <ul class=\"top-menu\">");
document.write("                    <li>");
document.write("                        <a href=\"products.html\">品牌<\/a>");
document.write("                    <\/li>");
document.write("                    <li>");
document.write("                        <a href=\"products.html\">娛樂<\/a>");
document.write("                    <\/li>");
document.write("                    <li>");
document.write("                        <a href=\"products.html\">探險<\/a>");
document.write("                    <\/li>");
document.write("                    <li>");
document.write("                        <a href=\"winners.html\">贏家<\/a>");
document.write("                    <\/li>");
document.write("                    <li>");
document.write("                        <a href=\"blog.html\">部落格<\/a>");
document.write("                    <\/li>");
document.write("                    <li>");
document.write("                        <a href=\"about.html\">關於我們<\/a>");
document.write("                    <\/li>");
document.write("                    <div class=\"m-top-lang\">");
document.write("                        <span><img src=\"SRC\/images\/lang.svg\">繁中<\/span>");
document.write("<div class=\"drop-down\">");
document.write("    <div class=\"drop-down-content\">");
document.write("    	<a href=\"\" class=\"drop-down-item\">繁中<\/a>");
document.write("        <a href=\"\" class=\"drop-down-item\">英文<\/a>                                ");
document.write("    <\/div>");
document.write("");
document.write("<\/div>");
document.write("                    <\/div>");
document.write("                <\/ul>");
document.write("                <ul class=\"top-menu-features\">");
document.write("                    <li class=\"top-lang hover-menu\">");
document.write("                        <span><img src=\"SRC\/images\/lang.svg\">繁中<\/span>");
document.write("<div class=\"drop-down\">");
document.write("    <div class=\"drop-down-content\">");
document.write("    	<a href=\"\" class=\"drop-down-item\">繁中<\/a>");
document.write("        <a href=\"\" class=\"drop-down-item\">英文<\/a>                                ");
document.write("    <\/div>");
document.write("");
document.write("<\/div>");
document.write("                    <\/li>");
document.write("                    <li class=\"top-member\">");
document.write("                        <a href=\"member_login.html\"><img src=\"SRC\/images\/user.svg\">登入<\/a>");
document.write("                    <\/li>");
document.write("                    <li class=\"top-gift\">");
document.write("                        <a href=\"shopcart.html\"><img src=\"SRC\/images\/gift.svg\"><span>1<\/span><\/a>");
document.write("                    <\/li>");
document.write("                <\/ul>                ");
document.write("            <\/div>");
document.write("");
document.write("            <div class=\"nav-bar\">");
document.write("                <span><\/span>");
document.write("                <span><\/span>");
document.write("                <span><\/span>");
document.write("                ");
document.write("            <\/div>          ");
document.write("        <\/div>");
document.write("");
document.write("    <div class=\"mask-bg\"><\/div>      ");
document.write("    <\/header>");
document.write("");
