document.write("<!DOCTYPE html>");
document.write("<html lang=\"zh-Hant-TW\">");
document.write("<head>");
document.write("<meta charset=\"UTF-8\">");
document.write("<meta name=\"viewport\" content=\"width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=yes\" \/>");
document.write("<title>捷羚機械有限公司<\/title>");
document.write("");
document.write("<link href=\"SRC\/css\/reset.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"SRC\/css\/layout.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"SRC\/css\/font.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"SRC\/css\/fontawesome-all.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"SRC\/css\/animate.min.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("<link type=\"text\/css\" rel=\"stylesheet\" href=\"SRC\/css\/jquery.mmenu.all.min.css\" \/>");
document.write("<link rel=\"stylesheet\" href=\"SRC\/fancybox\/jquery.fancybox.css\" \/>");
document.write("<link href=\"SRC\/css\/master.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<script src=\"SRC\/js\/jquery-1.8.3.min.js\"><\/script>");
document.write("<script type=\"text\/javascript\" src=\"SRC\/js\/top.js\"><\/script>");
document.write("<!--[if lt IE 9]>");
document.write("<script src=\"SRC\/js\/IE9.js\"><\/script>");
document.write("<script src=\"SRC\/js\/html5shiv.min.js\"><\/script>");
document.write("<script src=\"SRC\/js\/respond.min.js\"><\/script>");
document.write("<![endif]-->");
document.write("");
document.write("<!--fadeIn -->");
document.write("<script type=\"text\/javascript\" src=\"SRC\/js\/effect.js\"><\/script>");
document.write("<script>");
document.write("	\/\/ WOW JS");
document.write("	new WOW().init();");
document.write("	$(document).ready(function() {");
document.write("		");
document.write("	});");
document.write("<\/script>");
document.write("<!--\/\/fadeIn -->");
document.write("");
document.write("<!--ZOOM -->");
document.write("");
document.write("<link rel=\"shortcut icon\" href=\"images\/favicon\/favicon.png\" type=\"image\/x-icon\">");
document.write("<script src=\"SRC\/fancybox\/jquery.fancybox.js\" type=\"text\/javascript\"><\/script>");
document.write("<script type=\"text\/javascript\">");
document.write("		$(document).ready(function() {			");
document.write("			$('.fancybox').fancybox();");
document.write("			");
document.write("			");
document.write("		});");
document.write("<\/script>");
document.write("<!--\/\/ZOOM --> ");
document.write("");
document.write("");
document.write("<\/head>");
document.write("<body>");
document.write("<!--wrapper-->");
document.write("");
document.write("<div id=\"wrapper\">");
document.write("	<div class=\"mask-bg\"><\/div>	");
document.write("  <header>  ");
document.write("    <div class=\"header_pageHeader_box\"> ");
document.write("	    <div class=\"pageHeader\"> ");
document.write("		<div class=\"box-1\"> ");
document.write("  <div class=\"logo\"><a href=\"index.html\"><img src=\"images\/logo.svg\" alt=\"捷羚機械\" title=\"捷羚機械\"><\/a><\/div>  ");
document.write("  <div class=\"menubox\"> ");
document.write("    <!--mobile menu -->");
document.write("    <div class=\"mobile_menu\">     ");
document.write("      <a href=\"#menu\" title=\"menu\">");
document.write("        <div class=\"hamburger\">");
document.write("          <div class=\"hamburger-box\">");
document.write("            <div class=\"hamburger-inner\"><\/div>");
document.write("          <\/div>");
document.write("        <\/div>");
document.write("      <\/a>       ");
document.write("    <\/div>");
document.write("    <nav id=\"menu\">");
document.write("      <ul> ");
document.write("        <li>");
document.write("          <span>關於捷羚<\/span>");
document.write("          <ul>");
document.write("            <li><a href=\"about.html\">公司簡介<\/a><\/li>");
document.write("            <li><a href=\"about.html\">公司組織<\/a><\/li>");
document.write("            <li><a href=\"about.html\">環境品質與政策<\/a><\/li>");
document.write("          <\/ul>");
document.write("        <\/li>");
document.write("        <li>");
document.write("          <span>產品展示<\/span>");
document.write("          <ul>");
document.write("            <li><a href=\"products.html\">TS系列<\/a><\/li>");
document.write("            <li><a href=\"products.html\">jl系列<\/a><\/li>  ");
document.write("          <\/ul>");
document.write("        <\/li>                      ");
document.write("        <li><a href=\"news.html\">最新消息<\/a><\/li>");
document.write("        <li><a href=\"download.html\">檔案下載<\/a><\/li>");
document.write("        <li><a href=\"faq.html\">常見問題<\/a><\/li>");
document.write("        <li>");
document.write("          <span>影音專區<\/span>");
document.write("          <ul>");
document.write("            <li><a href=\"video.html\">媒體採訪影片<\/a><\/li>");
document.write("            <li><a href=\"video.html\">展覽與表演<\/a><\/li>  ");
document.write("            <li><a href=\"video.html\">分類由後台建立<\/a><\/li>  ");
document.write("          <\/ul>");
document.write("        <\/li>      ");
document.write("        <li><a href=\"contact.html\">聯絡資訊<\/a><\/li>");
document.write("      <\/ul>            ");
document.write("    <\/nav>");
document.write("    <!--\/\/mobile menu -->");
document.write("    <div class=\"earth\">");
document.write("      <a href=\"#language_box\" class=\"fancybox\"><img src=\"images\/earth.png\"><\/a>");
document.write("    <\/div>");
document.write("    <div class=\"search\">");
document.write("      <a href=\"#search_box\" class=\"fancybox\"><img src=\"images\/search.png\"><\/a>");
document.write("    <\/div>");
document.write("    <!--web menu -->");
document.write("    <nav role=\"navigation\" class=\"nav\">");
document.write("      <ul class=\"nav-items\">");
document.write("        <li class=\"nav-item\">");
document.write("          <a href=\"about.html\" class=\"nav-link\"><span>關於捷羚<\/span><\/a>");
document.write("        <\/li> ");
document.write("        <li class=\"nav-item\">");
document.write("          <a href=\"products.html\" class=\"nav-link\"><span>產品展示<\/span><\/a>");
document.write("        <\/li>");
document.write("        <li class=\"nav-item\">");
document.write("          <a href=\"news.html\" class=\"nav-link\"><span>最新消息<\/span><\/a>");
document.write("        <\/li> ");
document.write("        <li class=\"nav-item\">");
document.write("          <a href=\"download.html\" class=\"nav-link\"><span>檔案下載<\/span><\/a>");
document.write("        <\/li>");
document.write("        <li class=\"nav-item\">");
document.write("          <a href=\"faq.html\" class=\"nav-link\"><span>常見問題<\/span><\/a>");
document.write("        <\/li>");
document.write("        <li class=\"nav-item\">");
document.write("          <a href=\"video.html\" class=\"nav-link\"><span>影音專區<\/span><\/a>");
document.write("        <\/li> ");
document.write("        <li class=\"nav-item\">");
document.write("          <a href=\"contact.html\" class=\"nav-link\"><span>聯絡資訊<\/span><\/a>");
document.write("        <\/li>");
document.write("      <\/ul>");
document.write("    <\/nav>");
document.write("    <!--\/\/web menu --> ");
document.write("  <\/div>");
document.write("<\/div>     ");
document.write("	    <\/div>");
document.write("    <\/div>");
document.write("  <\/header>");
document.write("  ");
document.write("  <!-- search-box -->");
document.write("  <div id=\"search_box\" class=\"fancy-box\">");
document.write("    <section style=\"margin-top:20px;\">");
document.write("	  <form action=\"search.html\" method=\"get\">");
document.write("	    <ul class=\"search-bar\">");
document.write("	      <li><input type=\"search\" id=\"keyword\" name=\"keyword\" placeholder=\"請輸入關鍵字搜尋產品…\" \/><\/li>");
document.write("	      <li><input type=\"submit\" value=\"搜尋\" \/><\/li>");
document.write("	    <\/ul>");
document.write("	  <\/form>");
document.write("    <\/section>");
document.write("  <\/div><!-- \/\/search-box -->");
document.write("  <!-- search-box -->");
document.write("  <div id=\"language_box\" class=\"fancy-box\">");
document.write("    <section style=\"margin-top:20px;\">");
document.write("	  <div class=\"language_box\">");
document.write("        <ul>");
document.write("	      <li><a href=\"index.html\">繁體中文<\/a><\/li>");
document.write("	      <li><a href=\"index.html\">English<\/a><\/li>");
document.write("        <\/ul>");
document.write("	  <\/div>");
document.write("    <\/section>");
document.write("  <\/div><!-- \/\/search-box -->");
document.write("  ");
document.write("<!--mobile  menu -->");
document.write("");
document.write("<script type=\"text\/javascript\" src=\"SRC\/js\/jquery.mmenu.all.min.js\"><\/script>");
document.write("<script type=\"text\/javascript\">");
document.write("	$(function() {");
document.write("		$('nav#menu').mmenu();");
document.write("		$('nav#menu').css('opacity','1');");
document.write("	});");
document.write("<\/script>");
document.write("<!-- \/\/mobile menu -->");
