document.writeln('<div class="box-1"> ');
document.writeln('  <div class="logo"><a href="index.html"><img src="images/logo.svg" alt="捷羚機械" title="捷羚機械"></a></div>  ');
document.writeln('  <div class="menubox"> ');
document.writeln('    <!--mobile menu -->');
document.writeln('    <div class="mobile_menu">     ');
document.writeln('      <a href="#menu" title="menu">');
document.writeln('        <div class="hamburger">');
document.writeln('          <div class="hamburger-box">');
document.writeln('            <div class="hamburger-inner"></div>');
document.writeln('          </div>');
document.writeln('        </div>');
document.writeln('      </a>       ');
document.writeln('    </div>');
document.writeln('    <nav id="menu">');
document.writeln('      <ul> ');
document.writeln('        <li>');
document.writeln('          <span>關於捷羚</span>');
document.writeln('          <ul>');
document.writeln('            <li><a href="about.html">公司簡介</a></li>');
document.writeln('            <li><a href="about.html">公司組織</a></li>');
document.writeln('            <li><a href="about.html">環境品質與政策</a></li>');
document.writeln('          </ul>');
document.writeln('        </li>');
document.writeln('        <li>');
document.writeln('          <span>產品展示</span>');
document.writeln('          <ul>');
document.writeln('            <li><a href="products.html">TS系列</a></li>');
document.writeln('            <li><a href="products.html">jl系列</a></li>  ');
document.writeln('          </ul>');
document.writeln('        </li>                      ');
document.writeln('        <li><a href="news.html">最新消息</a></li>');
document.writeln('        <li><a href="download.html">檔案下載</a></li>');
document.writeln('        <li><a href="faq.html">常見問題</a></li>');
document.writeln('        <li>');
document.writeln('          <span>影音專區</span>');
document.writeln('          <ul>');
document.writeln('            <li><a href="video.html">媒體採訪影片</a></li>');
document.writeln('            <li><a href="video.html">展覽與表演</a></li>  ');
document.writeln('            <li><a href="video.html">分類由後台建立</a></li>  ');
document.writeln('          </ul>');
document.writeln('        </li>      ');
document.writeln('        <li><a href="contact.html">聯絡資訊</a></li>');
document.writeln('      </ul>            ');
document.writeln('    </nav>');
document.writeln('    <!--//mobile menu -->');
document.writeln('    <div class="earth">');
document.writeln('      <a href="#language_box" class="fancybox"><img src="images/earth.png"></a>');
document.writeln('    </div>');
document.writeln('    <div class="search">');
document.writeln('      <a href="#search_box" class="fancybox"><img src="images/search.png"></a>');
document.writeln('    </div>');
document.writeln('    <!--web menu -->');
document.writeln('    <nav role="navigation" class="nav">');
document.writeln('      <ul class="nav-items">');
document.writeln('        <li class="nav-item">');
document.writeln('          <a href="about.html" class="nav-link"><span>關於捷羚</span></a>');
document.writeln('        </li> ');
document.writeln('        <li class="nav-item">');
document.writeln('          <a href="products.html" class="nav-link"><span>產品展示</span></a>');
document.writeln('        </li>');
document.writeln('        <li class="nav-item">');
document.writeln('          <a href="news.html" class="nav-link"><span>最新消息</span></a>');
document.writeln('        </li> ');
document.writeln('        <li class="nav-item">');
document.writeln('          <a href="download.html" class="nav-link"><span>檔案下載</span></a>');
document.writeln('        </li>');
document.writeln('        <li class="nav-item">');
document.writeln('          <a href="faq.html" class="nav-link"><span>常見問題</span></a>');
document.writeln('        </li>');
document.writeln('        <li class="nav-item">');
document.writeln('          <a href="video.html" class="nav-link"><span>影音專區</span></a>');
document.writeln('        </li> ');
document.writeln('        <li class="nav-item">');
document.writeln('          <a href="contact.html" class="nav-link"><span>聯絡資訊</span></a>');
document.writeln('        </li>');
document.writeln('      </ul>');
document.writeln('    </nav>');
document.writeln('    <!--//web menu --> ');
document.writeln('  </div>');
document.writeln('</div>   ');
