document.writeln('	<footer class="footer">');
document.writeln('		<div class="inner">');
document.writeln('			<a href="" class="fb-btn"><img src="SRC/images/fb.svg"></a>');
document.writeln('			<div class="footer-contact">');
document.writeln('				<div class="title">聯絡資訊</div>');
document.writeln('');
document.writeln('				周一~周五(每周六/日國定假日公休)<br>');
document.writeln('				0937-950978<br>');
document.writeln('				2009@livemail.tw');
document.writeln('			</div>');
document.writeln('			<a href="privacy.html" class="privacy">隱私權政策</a>');
document.writeln('			<div class="copyright">');
document.writeln('				Copyright © 2019 Dalls & Co. All rights reserved ');
document.writeln('				<a href="http://www.jddt.tw/" target="_blank">Designed by JDDT</a>');
document.writeln('			</div>			');
document.writeln('		</div>');
document.writeln('	</footer>');
document.writeln('');
document.writeln('');
document.writeln('    <!--== all js ==-->');
document.writeln('    <script type="text/javascript" src="SRC/js/1.12.4_jquery.min.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/venobox/venobox.min.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/slick.js"></script>');
document.writeln('    <script src="SRC/js/jquery.zoom.min.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/jquery.twzipcode.min.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/main.js"></script>');
document.writeln('</body>');
document.writeln('');
document.writeln('');
document.writeln('</html>');
