document.writeln('<!DOCTYPE html>');
document.writeln('<html>');
document.writeln('<head>');
document.writeln('    <meta charset="utf-8">');
document.writeln('    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">');
document.writeln('    <meta name="viewport" content="width=device-width initial-scale=1.0 user-scalable=yes">');
document.writeln('    <meta name="format-detection" content="telephone=no">');
document.writeln('    <title>Dlls & Co.女孩們的天堂</title>');
document.writeln('    <!--[if IE]>');
document.writeln('    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">``');
document.writeln('    <![endif]-->');
document.writeln('     <link rel="apple-touch-icon" href="SRC/images/favicon/favicon.png">');
document.writeln('    <link rel="shortcut icon" href="SRC/images/favicon/favicon.ico" type="image/x-icon">');
document.writeln('    <link rel="bookmark" href="SRC/images/favicon/favicon.ico" type="image/x-icon">');
document.writeln('    <meta name="Keywords" content="Dlls & Co.女孩們的天堂">');
document.writeln('    <meta name="Description" content="">');
document.writeln('    <meta name="Robots" content="All">');
document.writeln('    <meta http-equiv="content-language" content="zh-tw">');
document.writeln('    <!-- og -->');
document.writeln('    <meta property="og:title" content="Dlls & Co.女孩們的天堂">');
document.writeln('    <meta property="og:type" content="website">');
document.writeln('    <meta property="og:image" content="SRC/images/og.png">');
document.writeln('    <meta property="og:url" content="">');
document.writeln('    <link href="SRC/css/master.css" rel="stylesheet" type="text/css">');
document.writeln('');
document.writeln('</head>');
document.writeln('');
document.writeln('<body >');
document.writeln('');
document.writeln('<header>');
document.writeln('    <div class="inner">');
document.writeln('        <div class="header-top">');
document.writeln('            <a class="logo" href="index.html"><img src="SRC/images/logo.svg"></a>');
document.writeln('            <div class="header-right">');
document.writeln('                <div class="hide-1024"><script src="SRC/js/_search.js"></script></div>');
document.writeln('                <a href="member_login.html" class="user-icon"><img src="SRC/images/user.svg"></a>');
document.writeln('                <div class="shopcart-icon">');
document.writeln('                    <a href="shopping.html"><img src="SRC/images/shop.svg"><span class="num">1</span></a>');
document.writeln('                    <div class="shopcart-hover hide-1024">');
document.writeln('                        <!-- 一筆 -->');
document.writeln('                        <div class="shopcart-item">');
document.writeln('                            <a href="products_detail.html"><img class="pro-img-in" src="SRC/images/demo/02.jpg"></a>');
document.writeln('                            <div class="s-h-l">');
document.writeln('                                <div class="x-del">X</div>');
document.writeln('                                <p>A54247999</p>');
document.writeln('                                <div class="pro-r-name">簡約條紋百搭上衣</div>');
document.writeln('                                <!-- 顏色 -->');
document.writeln('                                <div>顏色：黑</div>');
document.writeln('                                <!-- size -->');
document.writeln('                                <div>尺寸：S</div>');
document.writeln('                                <!-- 數量 -->');
document.writeln('                                <div>數量：1</div>');
document.writeln('                                <p>$800</p>                           ');
document.writeln('                            </div>');
document.writeln('                        </div>');
document.writeln('                        <!-- 一筆 end-->');
document.writeln('                        <div class="shopcart-item">');
document.writeln('                            <a href="products_detail.html"><img class="pro-img-in" src="SRC/images/demo/02.jpg"></a>');
document.writeln('                            <div class="s-h-l">');
document.writeln('                                <div class="x-del">X</div>');
document.writeln('                                <p>A54247999</p>');
document.writeln('                                <div class="pro-r-name">簡約條紋百搭上衣</div>');
document.writeln('                                <div>顏色：黑</div>');
document.writeln('                                <div>尺寸：S</div>');
document.writeln('                                <div>數量：1</div>');
document.writeln('                                <p>$800</p>                           ');
document.writeln('                            </div>');
document.writeln('                        </div>');
document.writeln('                        <div class="shopcart-item">');
document.writeln('                            <a href="products_detail.html"><img class="pro-img-in" src="SRC/images/demo/02.jpg"></a>');
document.writeln('                            <div class="s-h-l">');
document.writeln('                                <div class="x-del">X</div>');
document.writeln('                                <p>A54247999</p>');
document.writeln('                                <div class="pro-r-name">簡約條紋百搭上衣</div>');
document.writeln('                                <div>顏色：黑</div>');
document.writeln('                                <div>尺寸：S</div>');
document.writeln('                                <div>數量：1</div>');
document.writeln('                                <p>$800</p>                           ');
document.writeln('                            </div>');
document.writeln('                        </div> ');
document.writeln('                        <div class="shopcart-item">');
document.writeln('                            <a href="products_detail.html"><img class="pro-img-in" src="SRC/images/demo/02.jpg"></a>');
document.writeln('                            <div class="s-h-l">');
document.writeln('                                <div class="x-del">X</div>');
document.writeln('                                <p>A54247999</p>');
document.writeln('                                <div class="pro-r-name">簡約條紋百搭上衣</div>');
document.writeln('                                <div>顏色：黑</div>');
document.writeln('                                <div>尺寸：S</div>');
document.writeln('                                <div>數量：1</div>');
document.writeln('                                <p>$800</p>                           ');
document.writeln('                            </div>');
document.writeln('                        </div> ');
document.writeln('                        <div class="shop-total">');
document.writeln('                            <div class="s-t"><span>小計</span><span>$2,997</span></div>');
document.writeln('                        </div>');
document.writeln('                        <a href="shopping.html">結&nbsp&nbsp&nbsp帳</a>');
document.writeln('                    </div>                    ');
document.writeln('                </div>');
document.writeln('');
document.writeln('');
document.writeln('                <div class="nav-bar show-1024">');
document.writeln('                    <span></span>');
document.writeln('                    <span></span>');
document.writeln('                    <span></span>');
document.writeln('                </div>    ');
document.writeln('            </div>            ');
document.writeln('        </div>');
document.writeln(' ');
document.writeln('        <nav class="nav">');
document.writeln('            <div class="close-btn">');
document.writeln('                <span></span>');
document.writeln('                <span></span>');
document.writeln('            </div>');
document.writeln('            <div class="show-1024"><script src="SRC/js/_search.js"></script></div>');
document.writeln('            <div class="nav-a">');
document.writeln('                <div class="nav-title"><a href="index.html">全部商品</a></div>');
document.writeln('                <div class="nav-drop">');
document.writeln('                    <div class="">');
document.writeln('                        <a href="index.html">新品區</a>');
document.writeln('                        <a href="index.html">上衣</a>');
document.writeln('                        <a href="index.html">褲子</a>');
document.writeln('                        <a href="index.html">外套</a>  ');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('            </div>');
document.writeln('            <div class="nav-a"><a href="news.html">最新消息</a>');
document.writeln('            </div>');
document.writeln('            <div class="nav-a">');
document.writeln('                <div class="nav-title"><a href="qa.html">常見問題</a></div>');
document.writeln('                <div class="nav-drop">');
document.writeln('                    <div class="">');
document.writeln('                        <a href="qa.html">商品說明</a>');
document.writeln('                        <a href="qa.html">購物流程</a>');
document.writeln('                        <a href="qa.html">付款與運送</a>');
document.writeln('                        <a href="qa.html">售後服務</a>');
document.writeln('                        <a href="qa.html">會員權益</a>');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('            </div>');
document.writeln('            <div class="nav-a"><a href="contact.html">留言板</a>');
document.writeln('        </nav>');
document.writeln('    </div>');
document.writeln('</header>');
document.writeln('');
