document.writeln('<div class="order-jump O-a-j" action="">');
document.writeln('	<div class="order-jump-inner">');
document.writeln('		<div class="jump-x close-bt"></div>');
document.writeln('		<div class="m-scroll">');
document.writeln('			<form>');
document.writeln('				<div class="title">訂單詢問</div>');
document.writeln('				<div class="form_flex l-30"><span>訂單編號</span>20182723410</div>');
document.writeln('				<div class="form_flex l-30"><span>姓名</span>張先生</div>	');
document.writeln('				<div class="form_flex">			');
document.writeln('					<input type="email" name="email" placeholder="Email">');
document.writeln('				</div>');
document.writeln('				<div class="form_flex">');
document.writeln('					<input onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')" placeholder="聯絡電話">');
document.writeln('				</div>');
document.writeln('				<div class="form_flex">');
document.writeln('					<textarea placeholder="詢問內容"></textarea>');
document.writeln('				</div>');
document.writeln('				<div class="f-s">');
document.writeln('					<button type="reset" class="btn2">重新填寫</button>');
document.writeln('					<button type="submit" class="btn1">送出意見</button>');
document.writeln('				</div>		');
document.writeln('			</form>			');
document.writeln('		</div>');
document.writeln('		');
document.writeln('	</div>');
document.writeln('</div>');
