document.write("	<footer class=\"footer\">");
document.write("		<div class=\"inner\">");
document.write("		<ul class=\"share-icon\">");
document.write("			<li><a href=\"\"><img src=\"SRC\/images\/fb-w.svg\"><\/a><\/li>");
document.write("			<li><a href=\"\"><img src=\"SRC\/images\/line-w.svg\"><\/a><\/li>");
document.write("			<li><a href=\"\"><img src=\"SRC\/images\/yt-w.svg\"><\/a><\/li>");
document.write("			<li><a href=\"\"><img src=\"SRC\/images\/ig-w.svg\"><\/a><\/li>");
document.write("		<\/ul>");
document.write("<ul class=\"f-link\">");
document.write("	<li><a href=\"contact.html\">聯絡我們<\/a><\/li>");
document.write("	<li><a href=\"publish.html\">廣告刊登<\/a><\/li>");
document.write("	<li><a href=\"\">徵才專區<\/a><\/li>");
document.write("	<li><a href=\"\">隱私權規範<\/a><\/li>");
document.write("<\/ul>");
document.write("");
document.write("			<a href=\"index.html\" class=\"logo\"><img src=\"SRC\/images\/logo-w.png\"><\/a>");
document.write("		<\/div>");
document.write("		<div class=\"copy-right\">");
document.write("			© 2021 worthy ALL RIGHTS RESERVED. ");
document.write("		<\/div>");
document.write("	<\/footer>");
document.write("");
document.write("    <!--== all js ==-->");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/1.12.4_jquery.min.js\"><\/script>");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/main.js\"><\/script>");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/slick.min.js\"><\/script>");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/owl.carousel.min.js\"><\/script>");
document.write("   <!-- <script type=\"text\/javascript\" src=\"https:\/\/cdn-cani.fonlego.com\/\/plugin\/owl.carousel-2.0.0\/owl.carousel.min.js\"><\/script> -->");
document.write("<\/body>");
document.write("");
document.write("");
document.write("<\/html>");
