document.write("<!doctype html>");
document.write("<html>");
document.write("<head>");
document.write("    <meta charset=\"UTF-8\">");
document.write("    <meta name=\"viewport\" content=\"width=device-width initial-scale=1.0 user-scalable=yes\">");
document.write("    <title>ㄧ值 Its Worthy<\/title>");
document.write("    <meta name=\"keywords\" content=\"\">");
document.write("    <meta name=\"description\" content=\"\">");
document.write("    <meta name=\"author\" content=\"ㄧ值 Its Worthy\">");
document.write("    <meta name=\"rating\" content=\"general\">");
document.write("    <meta name=\"robots\" content=\"all\">");
document.write("    <meta http-equiv=\"content-language\" content=\"zh-tw\">");
document.write("    <meta property=\"og:title\" content=\"ㄧ值 Its Worthy\">");
document.write("    <meta property=\"og:type\" content=\"website\">");
document.write("    <meta property=\"og:url\" content=\"\">");
document.write("    <meta property=\"og:image\" content=\"SRC\/images\/wejade-og.png\">");
document.write("    <meta property=\"og:description\" content=\"ㄧ值 Its Worthy\">");
document.write("    <link rel=\"apple-touch-icon\" href=\"SRC\/images\/apple-icon.png\">");
document.write("    <link rel=\"shortcut icon\" href=\"SRC\/images\/favicon\/favicon.ico\" type=\"image\/x-icon\">");
document.write("    <link rel=\"bookmark\" href=\"SRC\/images\/favicon\/favicon.ico\" type=\"image\/x-icon\">");
document.write("    <link href=\"SRC\/css\/master.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("");
document.write("<\/head>");
document.write("");
document.write("<body>");
document.write("");
document.write("<header>");
document.write("    <div class=\"inner\">");
document.write("        <div class=\"logo\"><a href=\"index.html\"><img src=\"SRC\/images\/logo.png\"><\/a><\/div>");
document.write("        <div class=\"nav-bar show-1200\" >");
document.write("            <span><\/span>");
document.write("            <span><\/span>");
document.write("        <\/div>");
document.write("        <nav class=\"menu-nav\">");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"hide-1200\" href=\"news.html\">樂趣捐<\/a>");
document.write("                <div class=\"show-1200\"><a href=\"news.html\">樂趣捐<\/a> <\/div>");
document.write("                <div class=\"menu-drop\"><a href=\"news.html\">次分類一<\/a><a href=\"news.html\">次分類二<\/a><a href=\"news.html\">次分類三<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"hide-1200\" href=\"news.html\">品牌<\/a>");
document.write("                <div class=\"show-1200\"><a href=\"news.html\">品牌<\/a><\/div>");
document.write("                <div class=\"menu-drop\"><a href=\"news.html\">次分類一<\/a><a href=\"news.html\">次分類二<\/a><a href=\"news.html\">次分類三<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"hide-1200\" href=\"news.html\">娛樂<\/a>");
document.write("                <div class=\"show-1200\"><a href=\"news.html\">娛樂<\/a><\/div>");
document.write("                <div class=\"menu-drop\"><a href=\"news.html\">次分類一<\/a><a href=\"news.html\">次分類二<\/a><a href=\"news.html\">次分類三<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"hide-1200\" href=\"news.html\">旅遊<\/a>");
document.write("                <div class=\"show-1200\"><a href=\"news.html\">旅遊<\/a><\/div>");
document.write("                <div class=\"menu-drop\"><a href=\"news.html\">次分類一<\/a><a href=\"news.html\">次分類二<\/a><a href=\"news.html\">次分類三<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"hide-1200\" href=\"news.html\">社會<\/a>");
document.write("                <div class=\"show-1200\"><a href=\"news.html\">社會<\/a><\/div>");
document.write("                <div class=\"menu-drop\"><a href=\"news.html\">次分類一<\/a><a href=\"news.html\">次分類二<\/a><a href=\"news.html\">次分類三<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"hide-1200\" href=\"news.html\">生活<\/a>");
document.write("                <div class=\"show-1200\"><a href=\"news.html\">生活<\/a><\/div>");
document.write("                <div class=\"menu-drop\"><a href=\"news.html\">次分類一<\/a><a href=\"news.html\">次分類二<\/a><a href=\"news.html\">次分類三<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"hide-1200\" href=\"news.html\">金融<\/a>");
document.write("                <div class=\"show-1200\"><a href=\"news.html\">金融<\/a><\/div>");
document.write("                <div class=\"menu-drop\"><a href=\"news.html\">次分類一<\/a><a href=\"news.html\">次分類二<\/a><a href=\"news.html\">次分類三<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"hide-1200\" href=\"news.html\">科技<\/a>");
document.write("                <div class=\"show-1200\"><a href=\"news.html\">科技<\/a><\/div>");
document.write("                <div class=\"menu-drop\"><a href=\"news.html\">次分類一<\/a><a href=\"news.html\">次分類二<\/a><a href=\"news.html\">次分類三<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"show-1200 footer\">");
document.write("            <ul class=\"share-icon\">");
document.write("                <li><a href=\"\"><img src=\"SRC\/images\/fb-w.svg\"><\/a><\/li>");
document.write("                <li><a href=\"\"><img src=\"SRC\/images\/line-w.svg\"><\/a><\/li>");
document.write("                <li><a href=\"\"><img src=\"SRC\/images\/yt-w.svg\"><\/a><\/li>");
document.write("                <li><a href=\"\"><img src=\"SRC\/images\/ig-w.svg\"><\/a><\/li>	");
document.write("            <\/ul>");
document.write("<ul class=\"f-link\">");
document.write("	<li><a href=\"contact.html\">聯絡我們<\/a><\/li>");
document.write("	<li><a href=\"publish.html\">廣告刊登<\/a><\/li>");
document.write("	<li><a href=\"\">徵才專區<\/a><\/li>");
document.write("	<li><a href=\"\">隱私權規範<\/a><\/li>");
document.write("<\/ul>");
document.write(" ");
document.write("            <\/div>");
document.write("");
document.write("        <\/nav>");
document.write("    <\/div>");
document.write("<\/header>");
document.write("<div class=\"mask-bg\"><\/div>");
