document.write( '	<footer>\n' );
document.write( '		<div class=\"inner\">\n' );
document.write( '			<div class=\"f-left\">\n' );
document.write( '				<img class=\"f-logo\" src=\"SRC/images/logo.svg\">\n' );
document.write( '				<span>303036 新竹縣湖口鄉光復南路33號</span>\n' );
document.write( '				<span>電話：<a href=\"tel:+88635973168\">+886-3-5973168</a></span>\n' );
document.write( '				<span>傳真：+886-3-5973166</span>\n' );
document.write( '				<ul class=\"share\">\n' );
document.write( '					<li><a href=\"\"><img src=\"SRC/images/fb.svg\"></a></li>\n' );
document.write( '					<li><a href=\"\"><img src=\"SRC/images/line.svg\"></a></li>\n' );
document.write( '					<li><a href=\"\"><img src=\"SRC/images/ig.svg\"></a></li>\n' );
document.write( '					<li><a href=\"\"><img src=\"SRC/images/yt.svg\"></a></li>\n' );
document.write( '				</ul>\n' );
document.write( '			</div>\n' );
document.write( '			<div class=\"f-right\" >\n' );
document.write( '				<ul>關於和淞\n' );
document.write( '	                <li><a href=\"about.html\">公司介紹</a></li>\n' );
document.write( '	                <li><a href=\"about2.html\">組織架構</a></li>\n' );
document.write( '	                <li><a href=\"about.html\">公司沿革</a></li>\n' );
document.write( '	                <li><a href=\"about.html\">服務據點</a></li>\n' );
document.write( '	                <li><a href=\"about.html\">品質與安衛政策</a></li>\n' );
document.write( '				</ul>\n' );
document.write( '				<ul>產品資訊\n' );
document.write( '					<li><a href=\"product.html\">代理經銷</a></li>\n' );
document.write( '					<li><a href=\"product.html\">廠務系統工程</a></li>\n' );
document.write( '					<li><a href=\"product.html\">設備製造ODM/OEM</a></li>\n' );
document.write( '					<li><a href=\"product.html\">醫材開發製造</a></li>\n' );
document.write( '				</ul>\n' );
document.write( '				<ul>新聞中心\n' );
document.write( '					<li><a href=\"news.html\">展覽活動</a></li>\n' );
document.write( '					<li><a href=\"news.html\">公司榮耀</a></li>\n' );
document.write( '					<li><a href=\"news.html\">認證</a></li>\n' );
document.write( '				</ul>\n' );
document.write( '				<ul>投資人專區\n' );
document.write( '					<li><a href=\"financial.html\">財務資訊</a></li>\n' );
document.write( '	                <li><a href=\"shareholder.html\">股東服務</a></li>\n' );
document.write( '	                <li><a href=\"governance.html\">公司治理</a></li>\n' );
document.write( '	                <li><a href=\"legal.html\">法人說明會資訊</a></li>\n' );
document.write( '	                <li><a href=\"invest.html\">聯絡洽詢</a></li>\n' );
document.write( '				</ul>\n' );
document.write( '				<ul>企業社會責任\n' );
document.write( '	                <li><a href=\"csr.html\">友善職場</a></li>\n' );
document.write( '	                <li><a href=\"csr.html\">供應商管理</a></li>\n' );
document.write( '	                <li><a href=\"csr2.html\">職業安全衛生管理</a></li>\n' );
document.write( '	                <li><a href=\"csr.html\">利害關係人</a></li>\n' );
document.write( '				</ul>\n' );
document.write( '				<ul>人力資源\n' );
document.write( '					<li><a href=\"resource.html\">教育訓練</a></li>\n' );
document.write( '					<li><a href=\"resource\">福利措施</a></li>\n' );
document.write( '					<li><a href=\"resource.html\">加入我們</a></li>\n' );
document.write( '				</ul>\n' );
document.write( '				<ul>線上諮詢\n' );
document.write( '					<li><a href=\"company.html\">公司資訊</a></li>\n' );
document.write( '					<li><a href=\"contact.html\">聯絡我們</a></li>\n' );
document.write( '				</ul>				\n' );
document.write( '			</div>\n' );
document.write( '		\n' );
document.write( '		</div>\n' );
document.write( '		<div class=\"inner copyright\">\n' );
document.write( '			<a href=\"privacy.html\">隱私權政策</a>\n' );
document.write( '			版權所有 © 2021 和淞科技股份有限公司\n' );
document.write( '			\n' );
document.write( '		</div>\n' );
document.write( '	</footer>\n' );
document.write( '	<div class=\"goTop-box\">\n' );
document.write( '	    <div class=\"goTop\">\n' );
document.write( '	    </div>		\n' );
document.write( '	</div>\n' );
document.write( '\n' );
document.write( '</body>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '<link rel=\"stylesheet\" href=\"SRC/fontawesome-free-5.15.1-web/css/all.min.css\">\n' );
document.write( '<link href=\"SRC/js/venobox/venobox.min.css\" rel=\"stylesheet\" type=\"text/css\">\n' );
document.write( '\n' );
document.write( '<script type=\"text/javascript\" src=\"SRC/js/venobox/venobox.min.js\"></script>\n' );
document.write( '<script type=\"text/javascript\" src=\"SRC/js/waypoints.min.js\"></script>\n' );
document.write( '<script type=\"text/javascript\" src=\"SRC/js/main.js\"></script>\n' );
document.write( '\n' );
document.write( '</html>' );
