document.write( '<!doctype html>\n' );
document.write( '<html>\n' );
document.write( '<head>\n' );
document.write( '    <meta charset=\"UTF-8\">\n' );
document.write( '    <meta name=\"viewport\" content=\"width=device-width initial-scale=1.0 user-scalable=yes\">\n' );
document.write( '    <title>和淞科技股份有限公司</title>\n' );
document.write( '    <meta name=\"keywords\" content=\"\">\n' );
document.write( '    <meta name=\"description\" content=\"\">\n' );
document.write( '    <meta name=\"author\" content=\"和淞科技\">\n' );
document.write( '    <meta name=\"rating\" content=\"general\">\n' );
document.write( '    <meta name=\"robots\" content=\"all\">\n' );
document.write( '    <meta http-equiv=\"content-language\" content=\"zh-tw\">\n' );
document.write( '    <meta property=\"og:title\" content=\"和淞科技\">\n' );
document.write( '    <meta property=\"og:type\" content=\"website\">\n' );
document.write( '    <meta property=\"og:url\" content=\"\">\n' );
document.write( '    <meta property=\"og:image\" content=\"SRC/images/og.jpg\">\n' );
document.write( '    <meta property=\"og:description\" content=\"和淞科技\">\n' );
document.write( '    <link rel=\"apple-touch-icon\" href=\"SRC/images/favicon/apple-icon.png\">\n' );
document.write( '    <link rel=\"shortcut icon\" href=\"SRC/images/favicon/favicon.png\" type=\"image/x-icon\">\n' );
document.write( '    <link rel=\"bookmark\" href=\"SRC/images/favicon/favicon.png\" type=\"image/x-icon\">\n' );
document.write( '    <link rel=\"stylesheet\" href=\"SRC/css/plugin.css\">\n' );
document.write( '    <link href=\"SRC/css/master.css\" rel=\"stylesheet\" type=\"text/css\">\n' );
document.write( '    <script type=\"text/javascript\" src=\"SRC/js/jquery-2.1.3.min.js\"></script>\n' );
document.write( '</head>\n' );
document.write( '\n' );
document.write( '<body>\n' );
document.write( '\n' );
document.write( '<header>\n' );
document.write( '\n' );
document.write( '    <a href=\"index.html\" class=\"logo\"><img src=\"SRC/images/logo.svg\"></a>\n' );
document.write( '    \n' );
document.write( '    <nav class=\"menu-nav\">\n' );
document.write( '        <div class=\"nav-a\">\n' );
document.write( '            <a href=\"about.html\">關於和淞</a>\n' );
document.write( '            <div class=\"nav-drop\">\n' );
document.write( '                <!-- 當前頁面加 active class \n' );
document.write( '                 例 <a class=\"active\" href=\"about.html\">公司發展</a> -->\n' );
document.write( '                <a href=\"about.html\">公司介紹</a>\n' );
document.write( '                <a href=\"about2.html\">組織架構</a>\n' );
document.write( '                <a href=\"about.html\">公司沿革</a>\n' );
document.write( '                <a href=\"about.html\">服務據點</a>\n' );
document.write( '                <a href=\"about.html\">品質與安衛政策</a>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"nav-a\">\n' );
document.write( '            <a href=\"product.html\">產品資訊</a>\n' );
document.write( '            <div class=\"nav-drop three-menu\">\n' );
document.write( '                <div class=\"menu-item\">\n' );
document.write( '                    <a href=\"product.html\">代理經銷</a>\n' );
document.write( '                    <div class=\"nav-sub-drop\">\n' );
document.write( '                        <a href=\"product.html\" class=\"active\">流量控制器</a>\n' );
document.write( '                        <a href=\"product.html\">晶圓量測器</a>\n' );
document.write( '                        <a href=\"product.html\">氣體純化設備</a>\n' );
document.write( '                        <a href=\"product.html\">廢棄除害設備</a>\n' );
document.write( '                        <a href=\"product.html\">光罩護膜</a>\n' );
document.write( '                        <a href=\"product.html\">濕式製程設備</a>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"menu-item\">\n' );
document.write( '                    <a href=\"product.html\">廠務系統工程</a>\n' );
document.write( '                    <div class=\"nav-sub-drop\">\n' );
document.write( '                        <a href=\"product.html\">氣體供應系統</a>\n' );
document.write( '                        <a href=\"product.html\">氣體監控系統</a>\n' );
document.write( '                        <a href=\"product.html\">化學供應系統</a>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"menu-item\">\n' );
document.write( '                    <a href=\"product.html\">設備製造ODM/OEM</a>\n' );
document.write( '                    <div class=\"nav-sub-drop\">\n' );
document.write( '                        <a href=\"product.html\">化學研磨供應系統</a>\n' );
document.write( '                        <a href=\"product.html\">FOUP/FOSB清洗設備</a>\n' );
document.write( '                        <a href=\"product.html\">零組件清洗設備</a>\n' );
document.write( '                        <a href=\"product.html\">AOI設備</a>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"menu-item\">\n' );
document.write( '                    <a href=\"product.html\">醫材開發製造</a>\n' );
document.write( '                    <div class=\"nav-sub-drop\">\n' );
document.write( '                        <a href=\"product.html\">噴霧片</a>\n' );
document.write( '                        <a href=\"product.html\">OEM/ODM</a>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"nav-a\">\n' );
document.write( '            <a href=\"news.html\">新聞中心</a>\n' );
document.write( '            <div class=\"nav-drop\">\n' );
document.write( '                <a href=\"news.html\">展覽活動</a>\n' );
document.write( '                <a href=\"news.html\">公司榮耀</a>\n' );
document.write( '                <a href=\"news.html\">認證</a>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"nav-a\">\n' );
document.write( '            <a href=\"financial.html\">投資人專區</a>\n' );
document.write( '            <div class=\"nav-drop\">\n' );
document.write( '                <div class=\"three-m\">\n' );
document.write( '                    <a href=\"financial.html\">財務資訊</a>\n' );
document.write( '                    <div class=\"nav-sub-drop\">\n' );
document.write( '                        <a href=\"financial.html\">每月營收報告</a>\n' );
document.write( '                        <a href=\"financial2.html\">財務報告</a>\n' );
document.write( '                        <a href=\"financial3.html\">新增頁面</a>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"three-m\">\n' );
document.write( '                  <a href=\"shareholder.html\">股東服務</a> \n' );
document.write( '                    <div class=\"nav-sub-drop\">\n' );
document.write( '                        <a href=\"shareholder.html\">股東會</a>\n' );
document.write( '                        <a href=\"shareholder2.html\">主要股東資訊</a>\n' );
document.write( '                        <a href=\"shareholder3.html\">股價查詢</a>\n' );
document.write( '                        <a href=\"shareholder3.html\">聯絡窗口</a>\n' );
document.write( '                        <a href=\"shareholder3.html\">新增頁面</a>\n' );
document.write( '                    </div> \n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"three-m\">\n' );
document.write( '                  <a href=\"governance.html\">公司治理</a> \n' );
document.write( '                    <div class=\"nav-sub-drop\">\n' );
document.write( '                        <a href=\"governance.html\">董事會</a>\n' );
document.write( '                        <a href=\"governance.html\">功能性委員會</a>\n' );
document.write( '                        <a href=\"governance2.html\">內部稽核</a>\n' );
document.write( '                        <a href=\"governance.html\">公司重要規章制度</a>\n' );
document.write( '                        <a href=\"governance2.html\">新增頁面</a>\n' );
document.write( '                    </div> \n' );
document.write( '                </div>\n' );
document.write( '                <a href=\"legal.html\">法人說明會資訊</a>\n' );
document.write( '                <a href=\"invest.html\">聯絡洽詢</a>\n' );
document.write( '                <a href=\"invest.html\">新增頁面</a>\n' );
document.write( '            </div>            \n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"nav-a\">\n' );
document.write( '            <a href=\"csr.html\">企業社會責任</a>\n' );
document.write( '             <div class=\"nav-drop\">\n' );
document.write( '                <a href=\"csr.html\">友善職場</a>\n' );
document.write( '                <a href=\"csr.html\">供應商管理</a>\n' );
document.write( '                <a href=\"csr2.html\">職業安全衛生管理</a>\n' );
document.write( '                <a href=\"csr.html\">利害關係人</a>\n' );
document.write( '                <a href=\"csr.html\">新增頁面</a>\n' );
document.write( '            </div>           \n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"nav-a\">\n' );
document.write( '            <a href=\"resource.html\">人力資源</a>\n' );
document.write( '             <div class=\"nav-drop\">\n' );
document.write( '                <a href=\"resource.html\">教育訓練</a>\n' );
document.write( '                <a href=\"resource.html\">福利措施</a>\n' );
document.write( '                <a href=\"resource.html\">加入我們</a>\n' );
document.write( '            </div>           \n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"nav-a\">\n' );
document.write( '            <a href=\"contact.html\">線上諮詢</a>\n' );
document.write( '             <div class=\"nav-drop\">\n' );
document.write( '                <a href=\"company.html\">公司資訊</a>\n' );
document.write( '                <a href=\"contact.html\">聯絡我們</a>\n' );
document.write( '            </div>           \n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"lang\">\n' );
document.write( '            <!-- 顯示當前語系 -->\n' );
document.write( '            LANGUAGE<i class=\"fas fa-chevron-down\"></i>\n' );
document.write( '            <!-- 顯示當前語系 END-->\n' );
document.write( '            <div class=\"lang-drop\">\n' );
document.write( '                <a href=\"\" class=\"active\">繁中</a>\n' );
document.write( '                <a href=\"\">English</a>\n' );
document.write( '                <a href=\"\">日語</a>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>\n' );
document.write( '    <div class=\"show-1600 m-search\"><i class=\"fas fa-search\"></i></div>\n' );
document.write( '    <div class=\"search-top\">\n' );
document.write( '        <form action=\"search.html\" class=\"search-form\">\n' );
document.write( '            <input type=\"text\" placeholder=\"產品搜尋\" name=\"search\">\n' );
document.write( '            <button type=\"submit\"><i class=\"fas fa-search\"></i></button>\n' );
document.write( '        </form>\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <div class=\"nav-bar show-1300\" >\n' );
document.write( '        <span></span>\n' );
document.write( '        <span></span>\n' );
document.write( '        <span></span>\n' );
document.write( '    </div>\n' );
document.write( '</header>\n' );
document.write( '<div class=\"mask-bg\"></div>' );
