document.writeln("    <div class=\'left-menu pro-left\'>");
document.writeln("        <h2 class=\'title\'>投資人專區</h2>");
document.writeln("        <!-- 一個分類 -->");
document.writeln("        <div class=\'sub-title\'>財務資訊</div>");
document.writeln("        <div class=\'sub-title-drop\' >");
document.writeln("            <!-- 當前頁面加 active class  -->");
document.writeln("            <a href=\'financial.html\' class=\'active\'>每月營收報告</a>");
document.writeln("            <a href=\'financial2.html\'>財務報告</a>");
document.writeln("            <a href=\'financial3.html\'>新增頁面</a>");
document.writeln("        </div>");
document.writeln("        <!-- 一個分類 END--> ");
document.writeln("");
document.writeln("        <div class=\'sub-title\'>股東服務</div>");
document.writeln("        <div class=\'sub-title-drop\' >");
document.writeln("	        <a href=\'shareholder.html\'>股東會</a>");
document.writeln("	        <a href=\'shareholder2.html\'>主要股東資訊</a>");
document.writeln("	        <a href=\'shareholder3.html\'>股價查詢</a>");
document.writeln("	        <a href=\'shareholder3.html\'>聯絡窗口</a>");
document.writeln("	        <a href=\'shareholder3.html\'>新增頁面</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'sub-title\'>公司治理</div>");
document.writeln("        <div class=\'sub-title-drop\' >");
document.writeln("	        <a href=\'governance.html\'>董事會</a>");
document.writeln("	        <a href=\'governance.html\'>功能性委員會</a>");
document.writeln("	        <a href=\'governance2.html\'>內部稽核</a>");
document.writeln("	        <a href=\'governance.html\'>公司重要規章制度</a>");
document.writeln("	        <a href=\'governance2.html\'>新增頁面</a>");
document.writeln("        </div>");
document.writeln("		<a href=\'legal.html\'>法人說明會資訊</a>");
document.writeln("		<a href=\'invest.html\'>聯絡洽詢</a>");
document.writeln("    </div>");
document.writeln("");