document.writeln("<div class=\'left-menu pro-left\'>");
document.writeln("    <h2 class=\'title\'>產品資訊</h2>");
document.writeln("    <!-- 一個分類 -->");
document.writeln("    <div class=\'sub-title\'>代理經銷</div>");
document.writeln("    <div class=\'sub-title-drop\' >");
document.writeln("        <!-- 當前頁面加 active class  -->");
document.writeln("        <a href=\'product.html\'>流量控制器</a>");
document.writeln("        <a href=\'product.html\' class=\'active\'>晶圓量測器</a>");
document.writeln("        <a href=\'product.html\'>氣體純化設備</a>");
document.writeln("        <a href=\'product.html\'>廢棄除害設備</a>");
document.writeln("        <a href=\'product.html\'>光罩護膜</a>");
document.writeln("        <a href=\'product.html\'>濕式製程設備</a>");
document.writeln("    </div>");
document.writeln("    <!-- 一個分類 END--> ");
document.writeln("");
document.writeln("    <div class=\'sub-title\'>廠務系統工程</div>");
document.writeln("        <div class=\'sub-title-drop\' >");
document.writeln("        <a href=\'product.html\'>氣體供應系統</a>");
document.writeln("        <a href=\'product.html\'>氣體監控系統</a>");
document.writeln("        <a href=\'product.html\'>化學供應系統</a>");
document.writeln("    </div>");
document.writeln("    <div class=\'sub-title\'>設備製造ODM/OEM</div>");
document.writeln("    <div class=\'sub-title-drop\' >");
document.writeln("        <a href=\'product.html\'>化學研磨供應系統</a>");
document.writeln("        <a href=\'product.html\'>FOUP/FOSB清洗設備</a>");
document.writeln("        <a href=\'product.html\'>零組件清洗設備</a>");
document.writeln("        <a href=\'product.html\'>AOI設備</a>");
document.writeln("    </div>");
document.writeln("    <div class=\'sub-title\'>醫材開發製造</div>");
document.writeln("    <div class=\'sub-title-drop\' >");
document.writeln("        <a href=\'product.html\'>噴霧片</a>");
document.writeln("        <a href=\'product.html\'>OEM/ODM</a>");
document.writeln("    </div> ");
document.writeln("</div>");
document.writeln("");