document.write("	<div class=\"go-top\">Go Top<\/div>");
document.write("	<footer class=\"footer\">");
document.write("		<div class=\"inner\">");
document.write("			<div class=\"footer-top\">");
document.write("				<div class=\"logo\"><img src=\"SRC\/images\/logo.png\">威峰創意行銷有限公司<\/div>");
document.write("				<ul class=\"f-share\">");
document.write("					<li><a href=\"\"><img src=\"SRC\/images\/fb.svg\"><\/a><\/li>");
document.write("					<li><a href=\"\"><img src=\"SRC\/images\/ig.svg\"><\/a><\/li>");
document.write("					<li><a href=\"\"><img src=\"SRC\/images\/line.svg\"><\/a><\/li>");
document.write("					<li><a href=\"\"><img src=\"SRC\/images\/youtube.svg\"><\/a><\/li>");
document.write("					<li><a href=\"\"><img src=\"SRC\/images\/message.svg\"><\/a><\/li>");
document.write("				<\/ul>");
document.write("			<\/div>");
document.write("			<div class=\"footer-bottom\">");
document.write("				<ul class=\"f-info\">");
document.write("					<li><img src=\"SRC\/images\/f-1.svg\">243 新北市泰山區楓樹街31號<\/li>");
document.write("					<li><img src=\"SRC\/images\/f-2.svg\">(02)2909-2689<\/li>");
document.write("					<li><img src=\"SRC\/images\/f-3.svg\">tinya.tu888@gmail.com<\/li>");
document.write("				<\/ul>");
document.write("				<div class=\"copyright\">");
document.write("					<a href=\"privacy.html\">隱私權政策<\/a>");
document.write("					<span>© 2022威峰創意行銷有限公司<\/span>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("			");
document.write("		<\/div>");
document.write("		");
document.write("	<\/footer>");
document.write("");
document.write("    <!--== all js ==-->");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/1.12.4_jquery.min.js\"><\/script>");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/main.js\"><\/script>");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/slick.min.js\"><\/script>");
document.write("    <script type=\"text\/javascript\" src=\"SRC\/js\/waypoints.min.js\"><\/script>");
document.write("   <!-- <script type=\"text\/javascript\" src=\"https:\/\/cdn-cani.fonlego.com\/\/plugin\/owl.carousel-2.0.0\/owl.carousel.min.js\"><\/script> -->");
document.write("<\/body>");
document.write("");
document.write("");
document.write("<\/html>");
