document.write("<!doctype html>");
document.write("<html>");
document.write("<head>");
document.write("    <meta charset=\"UTF-8\">");
document.write("    <meta name=\"viewport\" content=\"width=device-width initial-scale=1.0 user-scalable=yes\">");
document.write("    <title>威峰創意行銷有限公司<\/title>");
document.write("    <meta name=\"keywords\" content=\"\">");
document.write("    <meta name=\"description\" content=\"\">");
document.write("    <meta name=\"author\" content=\"威峰創意行銷有限公司\">");
document.write("    <meta name=\"rating\" content=\"general\">");
document.write("    <meta name=\"robots\" content=\"all\">");
document.write("    <meta http-equiv=\"content-language\" content=\"zh-tw\">");
document.write("    <meta property=\"og:title\" content=\"威峰創意行銷有限公司\">");
document.write("    <meta property=\"og:type\" content=\"website\">");
document.write("    <meta property=\"og:url\" content=\"\">");
document.write("    <meta property=\"og:image\" content=\"SRC\/images\/og.png\">");
document.write("    <meta property=\"og:description\" content=\"威峰創意行銷有限公司\">");
document.write("    <link rel=\"apple-touch-icon\" href=\"SRC\/images\/apple-icon.png\">");
document.write("    <link rel=\"shortcut icon\" href=\"SRC\/images\/favicon\/favicon.ico\" type=\"image\/x-icon\">");
document.write("    <link rel=\"bookmark\" href=\"SRC\/images\/favicon\/favicon.ico\" type=\"image\/x-icon\">");
document.write("    <link href=\"SRC\/css\/master.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("");
document.write("<\/head>");
document.write("");
document.write("<body>");
document.write("");
document.write("<header>");
document.write("    <div class=\"inner\">");
document.write("        <div class=\"logo\"><a href=\"index.html\"><img src=\"SRC\/images\/logo.png\"><\/a><\/div>");
document.write("        <div class=\"nav-bar show-1200\" >");
document.write("            <span><\/span>");
document.write("            <span><\/span><span><\/span>");
document.write("        <\/div>");
document.write("        <nav class=\"menu-nav\">");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"\" href=\"about.html\">關於威峰<\/a>");
document.write("                <div class=\"menu-drop\"><a href=\"about.html\">公司介紹<\/a><a href=\"about.html\">經營理念<\/a><a href=\"about.html\">組織團隊<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"\" href=\"service.html\">服務項目<\/a>");
document.write("                <div class=\"menu-drop\"><a href=\"service.html\">通路試吃行銷<\/a><a href=\"service.html\">購物平台<\/a><a href=\"service.html\">廣告設計<\/a><a href=\"service.html\">包裝視覺設計<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"\" href=\"work.html\">作品案例<\/a>");
document.write("                <div class=\"menu-drop\"><a href=\"work.html\">食品產業<\/a><a href=\"work.html\">零售與電商<\/a><a href=\"work.html\">美妝產業<\/a><a href=\"work.html\">其它<\/a><\/div>");
document.write("            <\/div>");
document.write("            <div class=\"menu-a\">");
document.write("                <a class=\"no-drop\" href=\"contact.html\" >聯絡我們<\/a>");
document.write("            <\/div>");
document.write("            <ul class=\"f-share\">");
document.write("                <li><a href=\"\"><img src=\"SRC\/images\/fb.svg\"><\/a><\/li>");
document.write("                <li><a href=\"\"><img src=\"SRC\/images\/ig.svg\"><\/a><\/li>");
document.write("                <li><a href=\"\"><img src=\"SRC\/images\/line.svg\"><\/a><\/li>");
document.write("                <li><a href=\"\"><img src=\"SRC\/images\/youtube.svg\"><\/a><\/li>");
document.write("                <li><a href=\"\"><img src=\"SRC\/images\/message.svg\"><\/a><\/li>");
document.write("            <\/ul>");
document.write("");
document.write("        <\/nav>            ");
document.write("        <form class=\"search-bar\" action=\"search.html\">");
document.write("                <input type=\"text\" placeholder=\"請輸入關鍵字\" name=\"search\">");
document.write("        <\/form>");
document.write("        <div class=\"search\">");
document.write("");
document.write("            <img src=\"SRC\/images\/search.svg\">");
document.write("            <div class=\"close\">");
document.write("                <span><\/span>");
document.write("            <\/div>");
document.write("            ");
document.write("        <\/div>");
document.write("");
document.write("    <\/div>");
document.write("<\/header>");
document.write("<div class=\"mask-bg\"><\/div>");
