document.writeln("<footer>");
document.writeln("		<div class=\"inner\">");
document.writeln("			<div class=\"footer-btn\">");
document.writeln("				<a href=\"tel:+886425375672\" ><img class=\"show-img\" src=\"public/SRC/images/tel-w.svg\"><img class=\"hover-img\" src=\"public/SRC/images/tel.svg\"><span>GIVE US A CALL</span></a>");
document.writeln("				<a href=\"request\"><img class=\"show-img\" src=\"public/SRC/images/mail-w.svg\"><img class=\"hover-img\" src=\"public/SRC/images/mail.svg\"><span>Request A  Quote</span></a> ");
document.writeln("				<a href=\"ask\"><img class=\"show-img\" src=\"public/SRC/images/ask-w.svg\"><img class=\"hover-img\" src=\"public/SRC/images/ask.svg\"><span>Ask A Question</span></a>		");
document.writeln("			</div>");
document.writeln("			<div class=\"footer-resources\">");
document.writeln("				<div class=\"footer-title\">Customer Resources</div>");
document.writeln("				<a href=\"Privacy_policy.php\">Privacy Policy</a>");
document.writeln("				<a href=\"Terms_Of_Use.php\">Terms Of Use</a>");
document.writeln("			</div>");
document.writeln("			<div class=\"footer-contact\">");
document.writeln("				<div class=\"footer-title\">Contact Information</div>");
document.writeln("				<div class=\"title\"><div class=\"title\"><img src=\"public/SRC/images/logo.svg\"></div></div>");
document.writeln("				<div>");
document.writeln("					<img src=\"public/SRC/images/map.svg\">");
document.writeln("					<a href=\"https://goo.gl/maps/TT2Jrwm3krDRznDB8\" target=\"_blank\">No. 47, Xianghe Rd., Tanzi Dist.,<br>Taichung City 42741,Taiwan (R.O.C.)</a>");
document.writeln("				</div>");
document.writeln("				<a href=\"tel:+886425375672\" ><img src=\"public/SRC/images/tel.svg\">+886-4-2537-5672</a>");
document.writeln("				<a href=\"mailto:sales@mail.gigatek.com.tw\"><img src=\"public/SRC/images/mail.svg\">sales@mail.gigatek.com.tw</a>");
document.writeln("			</div>");
document.writeln("			");
document.writeln("		</div>");
document.writeln("		<div class=\"copyright\"><span>© 2020 Gigatek Inc. ALL RIGHTS RESERVED.</span>|<a href=\"https://www.jddt.tw\">Designed by JDDT</a> </div>");
document.writeln("	</footer>");
document.writeln("");
document.writeln("	<!--LY_VIDEO_BOX-->		");
document.writeln("	<div class=\"video_all_bg\" style=\"display:none\">");
document.writeln("		<div class=\"video_photo_show\" style=\"display:block\">");
document.writeln("			<div class=\"video_photo_showbox\">");
document.writeln("				<a href=\"javascript: void(0)\"><div class=\"olcat_video\"></div></a>");
document.writeln("			</div>");
document.writeln("			<div>");
document.writeln("				<div class=\"video\">");
document.writeln("					<iframe src=\"https://www.youtube.com/embed/dN1x03aSlLg?enablejsapi=1\" frameborder=\"0\" allowfullscreen class=\"video123\"></iframe>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("				");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	");
document.writeln("	<!--== all js ==-->");
document.writeln("	<script type=\"text/javascript\" src=\"public/SRC/js/1.12.4_jquery.min.js\"></script>");
document.writeln("	<script type=\"text/javascript\" src=\"public/SRC/js/main.js\"></script>");
document.writeln("	<script type=\"text/javascript\" src=\"public/SRC/js/slick.min.js\"></script>   ");
document.writeln("	<script type=\"text/javascript\" src=\"public/SRC/js/venobox/venobox.min.js\"></script>");
document.writeln("	<script src=\"public/SRC/js/jquery.validate.min.js\"></script>");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("</html>");