document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width initial-scale=1.0 user-scalable=yes\'>");
document.writeln("    <title>Gigatek Inc</title>");
document.writeln("    <!--[if IE]>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge,chrome=1\'>");
document.writeln("    <![endif]-->");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'57x57\' href=\'public/SRC/images/apple-icon-57x57.png\'>");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'60x60\' href=\'public/SRC/images/apple-icon-60x60.png\'>");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'72x72\' href=\'public/SRC/images/apple-icon-72x72.png\'>");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'76x76\' href=\'public/SRC/images/apple-icon-76x76.png\'>");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'114x114\' href=\'public/SRC/images/apple-icon-114x114.png\'>");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'120x120\' href=\'public/SRC/images/apple-icon-120x120.png\'>");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'144x144\' href=\'public/SRC/images/apple-icon-144x144.png\'>");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'152x152\' href=\'public/SRC/images/apple-icon-152x152.png\'>");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'180x180\' href=\'public/SRC/images/apple-icon-180x180.png\'>");
document.writeln("    <link rel=\'icon\' type=\'image/png\' sizes=\'192x192\' href=\'public/SRC/images/android-icon-192x192.png\'>");
document.writeln("    <link rel=\'icon\' type=\'image/png\' sizes=\'32x32\' href=\'public/SRC/images/favicon-32x32.png\'>");
document.writeln("    <link rel=\'icon\' type=\'image/png\' sizes=\'96x96\' href=\'public/SRC/images/favicon-96x96.png\'>");
document.writeln("    <link rel=\'icon\' type=\'image/png\' sizes=\'16x16\' href=\'public/SRC/images/favicon-16x16.png\'>");
document.writeln("    <meta name=\'msapplication-TileImage\' content=\'public/SRC/images/ms-icon-144x144.png\'>");
document.writeln("    <link rel=\'shortcut icon\' href=\'/favicon.ico\' type=\'image/x-icon\'>");
document.writeln("    <meta name=\'Keywords\' content=\'Gigatek Inc\'>");
document.writeln("    <meta name=\'Description\' content=\'\'>");
document.writeln("    <meta name=\'Robots\' content=\'All\'>");
document.writeln("    <meta http-equiv=\'content-language\' content=\'zh-tw\'>");
document.writeln("    <!-- og -->");
document.writeln("    <meta property=\'og:title\' content=\'Gigatek Inc\'>");
document.writeln("    <meta property=\'og:type\' content=\'website\'>");
document.writeln("    <meta property=\'og:image\' content=\'public/SRC/images/wejade-og.jpg\'>");
document.writeln("    <meta property=\'og:url\' content=\'\'>");
document.writeln("    <meta property=\'og:url\' content=\'Gigatek Inc\'>");
document.writeln("    <link rel=\'preconnect\' href=\'https://fonts.gstatic.com\'>");
document.writeln("    <link href=\'https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap\' rel=\'stylesheet\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'public/SRC/fontawesome-free-5.15.1-web/css/all.min.css\'>");
document.writeln("    <link href=\'public/SRC/css/_normalize.css\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("    <link href=\'public/SRC/css/animate.css\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("    <link href=\'public/SRC/css/master.css?v=041302\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("    <link href=\'public/SRC/css/slick.css\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("    <link href=\'public/SRC/css/slick-theme.css\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("    <link href=\'public/SRC/js/venobox/venobox.min.css\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("    <!-- JS -->");
document.writeln("    <script type=\'text/javascript\' src=\'public/SRC/js/jquery-3.1.1.js\'></script>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("	<header>");
document.writeln("        <div class=\'inner\'>");
document.writeln("            <div class=\'logo\'>");
document.writeln("                <a href=\'index.html\'>               ");
document.writeln("                <img src=\'public/SRC/images/logo.svg\'></a>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("             <ul class=\'top-menu\'>");
document.writeln("                <li>");
document.writeln("                    <a href=\'about.html\' class=\'hide-1200\'>ABOUT</a>");
document.writeln("                    <div  class=\'drop show-1200\'>ABOUT<i class=\'fas fa-chevron-down\'></i></div>");
document.writeln("                    <div class=\'menu-drop\'>");
document.writeln("                        <a href=\'about.html\'>About GIGATEK</a>");
document.writeln("                        <a href=\'history.html\'>History</a>");
document.writeln("                        <a href=\'why_gigatek.html\'>WHY GIGATEK</a>");
document.writeln("                        <a href=\'locations.html\'>Worldwide Locations</a>");
document.writeln("                        <a href=\'csr.html\'>CSR</a>");
document.writeln("                        <a href=\'javascript:void(0)\' class=\'video_butt\'>Video</a>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'product_development.html\' class=\'hide-1200\'>SERVICES</a>");
document.writeln("                    <div class=\'drop show-1200\'>SERVICES<i class=\'fas fa-chevron-down\'></i></div>");
document.writeln("                    <div class=\'menu-drop\'>");
document.writeln("                        <a href=\'product_development.html\'>PRODUCT DEVELOPMENT</a>");
document.writeln("                        <a href=\'contract_manufacturing.html\'>CONTRACT MANUFACTURING</a>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                   <a href=\'quality.html\' class=\'drop\'>QUALITY</a> ");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'equipment.html\' class=\'drop\'>EQUIPMENT</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'group.html\' class=\'drop\'>GROUP</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'customer.html\' class=\'drop\'>CUSTOMER</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'news.html\' class=\'drop\'>news</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'contact.html\' class=\'drop\'>contact</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'retail_banking.html\' class=\'hide-1200\'>technology & industry</a>");
document.writeln("                    <div class=\'drop show-1200\'>technology&industry<i class=\'fas fa-chevron-down\'></i></div>");
document.writeln("                    <div class=\'menu-drop open\'>");
document.writeln("                        <a href=\'retail_banking.html\'>Retail & Banking</a>");
document.writeln("                        <a href=\'security.html\'>Security, Auto ID</a>");
document.writeln("                        <a href=\'iot.html\'>IoT</a>");
document.writeln("                        <a href=\'transportation.html\'>Transportation</a>");
document.writeln("                        <a href=\'medical.html\'>Medical</a>");
document.writeln("                        <a href=\'consumer.html\'>Consumer</a>");
document.writeln("                        <a href=\'industrial.html\'>Industrial</a>");
document.writeln("                        <a href=\'energy_management.html\'>Energy Management</a>");
document.writeln("                        <a href=\'audiovisual.html\'>Audiovisual</a>");
document.writeln("                        <a href=\'sport.html\'>Sport</a>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("            <div class=\'nav-bar show-1200\'>");
document.writeln("                <span></span>");
document.writeln("                <span></span>");
document.writeln("                <span></span>");
document.writeln("                ");
document.writeln("            </div>");
document.writeln("              ");
document.writeln("        </div>      ");
document.writeln("    </header>");
document.writeln("    <div class=\'m-bg\'></div>");
document.writeln("    <div class=\'shortcut\'>");
document.writeln("        <ul class=\'inner\'>");
document.writeln("            <li>");
document.writeln("                <a href=\'tel:+886425375672\' ><img class=\'show-img\' src=\'public/SRC/images/tel-w.svg\'><img class=\'hover-img\' src=\'public/SRC/images/tel.svg\'>+886-4-2537-5672</a>  ");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'contact.html\'><img class=\'show-img\' src=\'public/SRC/images/mail-w.svg\'><img class=\'hover-img\' src=\'public/SRC/images/mail.svg\'>Contact Us</a>  ");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'request.html\'><img class=\'show-img\'  src=\'public/SRC/images/request-w.svg\'><img class=\'hover-img\' src=\'public/SRC/images/request.svg\'>Request A Quote</a>   ");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'ask.html\'><img class=\'show-img\' src=\'public/SRC/images/ask-w.svg\'><img class=\'hover-img\' src=\'public/SRC/images/ask.svg\'>Ask A Question</a>  ");
document.writeln("            </li>");
document.writeln("                        ");
document.writeln("        </ul>");
document.writeln("");
document.writeln("    </div>");
document.writeln("");