
document.writeln("	<footer>");
document.writeln("		<div class=\'inner\'>");
document.writeln("			<img class=\'f-logo\' src=\'SRC/images/logo2.svg\'>");
document.writeln("			<ul class=\'f-info\'>");
document.writeln("				<li><span>Add</span>231 新北市新店區民權路108號9樓</li>");
document.writeln("				<li><span>Tel</span>+886-2-82191900</li>");
document.writeln("				<li><span>Fax</span>+886-2-82191860</li>");
document.writeln("				<li><span>Mail</span>miko@engya.com.tw</li>				");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'copyright\'>");
document.writeln("			<div class=\'inner\'>");
document.writeln("			© ENGYA TECHNOLOGY CO., LTD.  ALL RIGHTS RESERVED");
document.writeln("			<a href=\'privacy.html\'>隱私權政策</a>	");
document.writeln("			</div>			");
document.writeln("		</div>");
document.writeln("	</footer>");
document.writeln("	<div class=\'fixed-btn\'>");
document.writeln("		<a href=\'inquiry_view.html\' class=\'inquiry-btn\'>詢價<br>清單<br>(0)</a>");
document.writeln("		<a href=\'sample.html\' class=\'sample-btn\'>樣品<br>申請<br>(0)</a>		");
document.writeln("	</div>");
document.writeln("	<div class=\'goTop-box\'>");
document.writeln("	    <div class=\'goTop\'>");
document.writeln("	    	<img src=\'SRC/images/top.svg\'>");
document.writeln("	    	Page<br>");
document.writeln("	    	top");
document.writeln("	    </div>		");
document.writeln("	</div>");
document.writeln("");
document.writeln("</body>");
document.writeln("");
document.writeln("");
document.writeln("<script type=\'text/javascript\' src=\'SRC/js/jquery-2.1.3.min.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'SRC/js/plugin.js\'></script>");
document.writeln("");
document.writeln("");
document.writeln("</html>");