document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width initial-scale=1.0 user-scalable=yes\'>");
document.writeln("    <title>英吉亞科技股份有限公司</title>");
document.writeln("    <meta name=\'keywords\' content=\'\'>");
document.writeln("    <meta name=\'description\' content=\'\'>");
document.writeln("    <meta name=\'author\' content=\'英吉亞科技股份有限公司\'>");
document.writeln("    <meta name=\'rating\' content=\'general\'>");
document.writeln("    <meta name=\'robots\' content=\'all\'>");
document.writeln("    <meta http-equiv=\'content-language\' content=\'zh-tw\'>");
document.writeln("    <meta property=\'og:title\' content=\'英吉亞科技股份有限公司\'>");
document.writeln("    <meta property=\'og:type\' content=\'website\'>");
document.writeln("    <meta property=\'og:url\' content=\'\'>");
document.writeln("    <meta property=\'og:image\' content=\'SRC/images/og.jpg\'>");
document.writeln("    <meta property=\'og:description\' content=\'英吉亞科技股份有限公司\'>");
document.writeln("    <link rel=\'apple-touch-icon\' sizes=\'192x192\' href=\'SRC/images/favicon/apple-icon.png\'>");
document.writeln("    <link rel=\'shortcut icon\' href=\'SRC/images/favicon/favicon.png\' type=\'image/x-icon\'>");
document.writeln("    <link rel=\'bookmark\' href=\'SRC/images/favicon/favicon.png\' type=\'image/x-icon\'>");
document.writeln("");
document.writeln("    <link rel=\'stylesheet\' href=\'SRC/css/plugin.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'SRC/fontawesome-free-5.15.1-web/css/all.min.css\'>");
document.writeln("    <link href=\'SRC/css/master.css\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("<header>");
document.writeln("");
document.writeln("    <a href=\'index.html\' class=\'logo\'><img src=\'SRC/images/logo.svg\'></a>");
document.writeln("    ");
document.writeln("    <nav class=\'menu-nav\'>");
document.writeln("        <div class=\'nav-a\'>");
document.writeln("            <a href=\'about.html\'>公司介紹<span>About us</span></a>");
document.writeln("            <div class=\'nav-drop\'>");
document.writeln("                <a href=\'about.html\'>關於英吉亞</a>");
document.writeln("                <a href=\'about.html\'>組織架構</a>");
document.writeln("                <a href=\'about.html\'>公司沿革</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-a\'>");
document.writeln("            <a href=\'app.html\'>產品應用<span>Applications</span></a>");
document.writeln("            <div class=\'nav-drop\'>");
document.writeln("                <a class=\'show-1200\' href=\'app.html\'>All / 全部</a>");
document.writeln("                <a href=\'app_view.html\'>Smart Phone / 手機</a>");
document.writeln("                <a href=\'app_view.html\'>Hard Disk(HD) / 硬碟(高清)</a>");
document.writeln("                <a href=\'app_view.html\'>LED Lighting Device / LED照明装置</a>");
document.writeln("                <a href=\'app_view.html\'>Note book/NetBook / 筆記型電腦</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-a\'>");
document.writeln("            <a href=\'product.html\'>產品介紹<span>Products</span></a>");
document.writeln("            <div class=\'nav-drop\'>");
document.writeln("                <a href=\'product.html\'>Common Mode Choke</a>");
document.writeln("                <a href=\'product.html\'>Molding Type Power Inductor</a>");
document.writeln("                <a href=\'product.html\'>Shielded SMD Type Power Inductor</a>");
document.writeln("                <a href=\'product.html\'>Unshielded SMD Type Power Inductor</a>");
document.writeln("                <a href=\'product.html\'>Wire Wound Chip Inductor</a>");
document.writeln("            </div>");
document.writeln("        </div> ");
document.writeln("        <div class=\'nav-a\'>");
document.writeln("            <a href=\'download.html\'>檔案下載<span>Download</span></a>");
document.writeln("            <div class=\'nav-drop\'>");
document.writeln("                <a href=\'download.html\'>Product Content</a>");
document.writeln("                <a href=\'download.html\'>SGS</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'nav-a m-NoDrop\'>");
document.writeln("            <a  href=\'contact.html\'>聯絡我們<span>Contact</span></a>");
document.writeln("        </div>                         ");
document.writeln("    </nav>");
document.writeln("");
document.writeln("    <div class=\'header-right\'>");
document.writeln("        <div class=\'show-1600 m-search\'><img src=\'SRC/images/search.svg\'></div>");
document.writeln("        <div class=\'search-top\'>");
document.writeln("            <form action=\'search.html\' class=\'search-form\'>");
document.writeln("                <input type=\'text\' placeholder=\'產品搜尋\' name=\'search\'>");
document.writeln("            </form>");
document.writeln("        </div>");
document.writeln("        <div class=\'header-share\'>");
document.writeln("            <img src=\'SRC/images/share.svg\'>");
document.writeln("            <div class=\'share-drop\'>");
document.writeln("                <a href=\'\'><img src=\'SRC/images/youtube.svg\'>Youtube</a>");
document.writeln("                <a href=\'\'><img src=\'SRC/images/ig.svg\'>Instagram</a>");
document.writeln("                <a href=\'\'><img src=\'SRC/images/facebook.svg\'>Facebook</a>");
document.writeln("                <a href=\'\'><img src=\'SRC/images/line.svg\'>line</a>");
document.writeln("            </div>");
document.writeln("        </div>        ");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\'nav-bar show-1200\' >");
document.writeln("        <span></span>");
document.writeln("        <span></span>");
document.writeln("        <span></span>");
document.writeln("    </div>");
document.writeln("</header>");
document.writeln("<div class=\'mask-bg\'></div>");