document.writeln('	<footer>');
document.writeln('		<div class="footer">');
document.writeln('			<ul class="footer-follow">');
document.writeln('				<li class="f-title hide-1024">關注我們</li>');
document.writeln('				<li class="f-li"><a href=""><img src="SRC/images/fb.svg"></a></li>');
document.writeln('				<li class="f-li"><a href=""><img src="SRC/images/ig.jpg"></a></li>');
document.writeln('				<li class="f-li"><a href=""><img src="SRC/images/line.svg"></a></li>');
document.writeln('				<li class="f-li"><a href=""><img src="SRC/images/g-shop.png"></a></li>');
document.writeln('				<li class="f-li"><a href=""><img src="SRC/images/youtube.svg"></a></li>');
document.writeln('				<li class="f-title">訂閱電子報</li>');
document.writeln('				<li class="f-email">');
document.writeln('					<input name="email" id="email" type="email" placeholder="請輸入email"><button><i class="fas fa-envelope"></i></button></li>');
document.writeln('			</ul>');
document.writeln('			<ul class="footer-contact">');
document.writeln('				<li class="f-title">聯絡資訊</li>');
document.writeln('				<li class="f-li">公司地址：807 高雄市三民區三民街69、71號 (有實體店面請放心購買)</li>');
document.writeln('				<li class="f-li">客服專線：07-2881887、07-2881889</li>');
document.writeln('				<li class="f-li">客服信箱：joy5gm@jmail.com</li>');
document.writeln('				<li class="f-li">營業時間：星期一～星期五 （上午9:00~18:30）</li>');
document.writeln('			</ul>			');
document.writeln('		</div>');
document.writeln('		<div class="copyright">|<a href="clause.html">隱私權政策</a>| <span class="t1">© 2020 泰鑫工具有限公司 All Rights Reserved.</span><a class="t2" href="http://www.jddt.tw/" target="_blank">Designed by JDDT</a></div>');
document.writeln('	</footer>');
document.writeln('	');
document.writeln('	<script src="SRC/js/_mobile-bottom-menu_login.js"></script>');
document.writeln('	');
document.writeln('	<div class="go-top"><img src="SRC/images/top.svg"></div>');
document.writeln('');
document.writeln('');
document.writeln('	<script src="SRC/js/_mobile-menu.js"></script>');
document.writeln('');
document.writeln('	<div class="add-cart-info" style="display: none;"><img src="SRC/images/cart.svg">已加入購物車</div>');
document.writeln('	<div class="add-love-info" style="display: none;"><i class="fas fa-heart"></i>已加入喜愛清單</div>	');
document.writeln('    <!--== all js ==-->');
document.writeln('    <script type="text/javascript" src="SRC/js/1.12.4_jquery.min.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/main.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/slick.min.js"></script>   ');
document.writeln('    <script type="text/javascript" src="SRC/js/venobox/venobox.min.js"></script>');
document.writeln('</body>');
document.writeln('');
document.writeln('');
document.writeln('</html>>');