document.writeln('	<footer>');
document.writeln('		<div class="footer">');
document.writeln('			<ul class="footer-follow">');
document.writeln('				<li class="f-title hide-1024">關注我們</li>');
document.writeln('				<li class="f-li"><a href=""><img src="SRC/images/fb.svg"></a></li>');
document.writeln('				<li class="f-li"><a href=""><img src="SRC/images/ig.jpg"></a></li>');
document.writeln('				<li class="f-li"><a href=""><img src="SRC/images/line.svg"></a></li>');
document.writeln('				<li class="f-li"><a href=""><img src="SRC/images/g-shop.png"></a></li>');
document.writeln('				<li class="f-li"><a href=""><img src="SRC/images/youtube.svg"></a></li>');
document.writeln('				<li class="f-title">訂閱電子報</li>');
document.writeln('				<li class="f-email">');
document.writeln('					<input name="email" id="email" type="email" placeholder="請輸入email"><button><i class="fas fa-envelope"></i></button></li>');
document.writeln('			</ul>');
document.writeln('			<ul class="footer-contact">');
document.writeln('				<li class="f-title">聯絡資訊</li>');
document.writeln('				<li class="f-li"><span>公司地址：</span><a href="https://g.page/dltool?share" target="_blank">807 高雄市三民區三民街69、71號</a></li>');
document.writeln('				');
document.writeln('               <!--                  <li class="f-li"><span>客服專線：</span>');
document.writeln('                                    <a href="tel:07-2881887">07-2881887</a>、');
document.writeln('                                    <a href="tel:07-288188">07-288188</a>、');
document.writeln('                                </li> -->');
document.writeln('                <li class="f-li"><span>客服專線：</span><a href="tel:(07)2881887">(07)2881887</a>、<a href="tel:(07)2881889">(07)2881889</a>、<a href="tel:(07)2852796">(07)2852796</a></li>');
document.writeln('');
document.writeln('                ');
document.writeln('				<li class="f-li"><span>客服信箱：</span><a href="mailto:dltoolservice@gmail.com">dltoolservice@gmail.com</a></li>');
document.writeln('				<li class="f-li"><span>營業時間：</span>星期一～星期五 （上午9:00~18:30）</li>');
document.writeln('			</ul>			');
document.writeln('		</div>');
document.writeln('		<div class="copyright">|<a href="clause.html">隱私權政策</a>| <span class="t1">© 2020 泰鑫工具有限公司 All Rights Reserved.</span><a class="t2" href="http://www.jddt.tw/" target="_blank">Designed by JDDT</a></div>');
document.writeln('	</footer>');
document.writeln('');
document.writeln('	<script src="SRC/js/_mobile-bottom-menu.js"></script>');
document.writeln('	<div class="tel-fixed"><a href="tel:+072881887"><i class="fas fa-phone-alt"></i></a></div>');
document.writeln('	<div class="go-top"><img src="SRC/images/top.svg"></div>');
document.writeln('');
document.writeln('');
document.writeln('	<script src="SRC/js/_mobile-menu.js"></script>');
document.writeln('');
document.writeln('	<div class="add-cart-info" style="display: none;"><img src="SRC/images/cart.svg">已加入購物車</div>');
document.writeln('	<div class="add-love-info" style="display: none;"><i class="fas fa-heart"></i>已加入喜愛清單</div>	');
document.writeln('');
document.writeln('	<div class="cookie">');
document.writeln('		<div class="inner">');
document.writeln('			<div>本網站使用cookies以提昇您的使用體驗及統計網路流量相關資料。繼續使用本網站表示您同意我們使用cookies。<br><a href="https://www.dltool.com/tw/member/privacy" target="_blank">隱私權政策</a>提供更多關於cookies使用及停用的相關資訊。</div>');
document.writeln('			<span class="cookie-btn"  href="javascript:;">我接受</span>			');
document.writeln('		</div>');
document.writeln('');
document.writeln('	</div>');
document.writeln('	');
document.writeln('    <!--== all js ==-->');
document.writeln('    <script type="text/javascript" src="SRC/js/1.12.4_jquery.min.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/main.js"></script>');
document.writeln('    <script type="text/javascript" src="SRC/js/slick.min.js"></script>   ');
document.writeln('    <script type="text/javascript" src="SRC/js/venobox/venobox.min.js"></script>');
document.writeln('</body>');
document.writeln('');
document.writeln('');
document.writeln('</html>');