document.writeln('<!doctype html>');
document.writeln('<html>');
document.writeln('<head>');
document.writeln(' <meta charset="utf-8">');
document.writeln('    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">');
document.writeln('    <meta name="viewport" content="width=device-width initial-scale=1.0 user-scalable=yes">');
document.writeln('    <title>泰鑫工具有限公司</title>');
document.writeln('    <!--[if IE]>');
document.writeln('    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">``');
document.writeln('    <![endif]-->');
document.writeln('    <meta name="Keywords" content="泰鑫工具有限公司,達利商城">');
document.writeln('    <meta name="Description" content="銷售品牌-PUMA|STIHL|BOSCH|凱馳|RYOBI|AGP|Kress|STANLEY|ISHII,品項-電鑽|空壓機|鍊鋸|吹風機|打蠟機|砂輪機|攻牙機|氣動工具|電動工具|園林工具|割草機">');
document.writeln('    <meta name="Author" content="泰鑫工具有限公司">');
document.writeln('    <meta name="Robots" content="All">');
document.writeln('    <meta http-equiv="content-language" content="zh-tw">');
document.writeln('    <!-- og -->');
document.writeln('    <meta property="og:title" content="泰鑫工具有限公司">');
document.writeln('    <meta property="og:type" content="website">');
document.writeln('    <meta property="og:image" content="SRC/images/wejade-og.jpg">');
document.writeln('    <meta property="og:url" content="">');
document.writeln('    <meta property="og:url" content="泰鑫工具有限公司">');
document.writeln('    <link rel="apple-touch-icon" href="SRC/images/TEXDON.png">');
document.writeln('    <link rel="shortcut icon" href="SRC/images/favicon/favicon.ico" type="image/x-icon">');
document.writeln('    <link rel="bookmark" href="SRC/images/favicon/favicon.ico" type="image/x-icon">');
document.writeln('    <link rel="stylesheet" href="SRC/fontawesome-free-5.15.1-web/css/all.min.css">');
document.writeln('    <link href="SRC/css/_normalize.css" rel="stylesheet" type="text/css">');
document.writeln('    <link href="SRC/css/animate.css" rel="stylesheet" type="text/css">');
document.writeln('    <link href="SRC/css/master.css" rel="stylesheet" type="text/css">');
document.writeln('    <link href="SRC/css/slick.css" rel="stylesheet" type="text/css">');
document.writeln('    <link href="SRC/css/slick-theme.css" rel="stylesheet" type="text/css">');
document.writeln('    <link href="SRC/js/venobox/venobox.min.css" rel="stylesheet" type="text/css">');
document.writeln('</head>');
document.writeln('');
document.writeln('<body>');
document.writeln('  <header>');
document.writeln('        <div class="inner">');
document.writeln('            <div class="header-left">');
document.writeln('                <div class="logo"><a href="index.html"><img src="SRC/images/logo.svg"></a></div>');
document.writeln('                <div class="nav-bar show-1024">');
document.writeln('                    <span></span>');
document.writeln('                    <span></span>');
document.writeln('                    <span></span>');
document.writeln('                </div>');
document.writeln('                <div class="top-menu">');
document.writeln('                    <a href="about.html">公司介紹</a>');
document.writeln('                    <a href="news.html">最新消息</a>');
document.writeln('                    <a href="sale.html">活動專區</a>');
document.writeln('                    <div class="menu-hover">');
document.writeln('                        <a href="products.html">產品介紹</a>');
document.writeln('                        <div class="menu-sub">');
document.writeln('                            <div class="inner">');
document.writeln('                                <div class="menu-sub-box">');
document.writeln('                                    <a href="products.html">品牌分類</a>');
document.writeln('                                    <div class="menu-sub-item">');
document.writeln('                                        <a href="products.html">機台</a>');
document.writeln('                                        <a href="products.html">配件</a>');
document.writeln('                                        <a href="products.html">其他</a>');
document.writeln('                                    </div>');
document.writeln('                                </div>');
document.writeln('                                <div class="menu-sub-box">');
document.writeln('                                    <a href="products.html">電動工具</a>');
document.writeln('                                    <div class="menu-sub-item">');
document.writeln('                                        <a href="products.html">110V</a>');
document.writeln('                                        <a href="products.html">220V</a>');
document.writeln('                                        <a href="products.html">12V</a>');
document.writeln('                                        <a href="products.html">直流電</a>');
document.writeln('                                        <a href="products.html">充電式鋰電</a>');
document.writeln('                                    </div>');
document.writeln('                                </div>');
document.writeln('                                <div class="menu-sub-box">');
document.writeln('                                    <a href="products.html">氣動工具</a>');
document.writeln('                                    <div class="menu-sub-item">');
document.writeln('                                        <a href="products.html">打臘機</a>');
document.writeln('                                        <a href="products.html">扳手</a>');
document.writeln('                                    </div>');
document.writeln('                                </div>');
document.writeln('                                <div class="menu-sub-box">');
document.writeln('                                    <a href="products.html">農機具</a>');
document.writeln('                                    <div class="menu-sub-item">');
document.writeln('                                        <a href="products.html">割草機</a>');
document.writeln('                                        <a href="products.html">鼓風機</a>');
document.writeln('                                    </div>');
document.writeln('                                </div>');
document.writeln('                                <div class="menu-sub-box">');
document.writeln('                                    <a href="products.html">發電機</a>');
document.writeln('                                    <div class="menu-sub-item">');
document.writeln('                                        <a href="products.html">1200w</a>');
document.writeln('                                        <a href="products.html">2000w</a>');
document.writeln('                                        <a href="products.html">2400w</a>');
document.writeln('                                        <a href="products.html">3500w</a>');
document.writeln('                                    </div>');
document.writeln('                                </div> ');
document.writeln('                                <div class="menu-sub-box">');
document.writeln('                                    <a href="products.html">農機具</a>');
document.writeln('                                    <div class="menu-sub-item">');
document.writeln('                                        <a href="products.html">割草機</a>');
document.writeln('                                        <a href="products.html">鼓風機</a>');
document.writeln('                                    </div>');
document.writeln('                                </div>');
document.writeln('                                <div class="menu-sub-box">');
document.writeln('                                    <a href="products.html">發電機</a>');
document.writeln('                                    <div class="menu-sub-item">');
document.writeln('                                        <a href="products.html">1200w</a>');
document.writeln('                                        <a href="products.html">2000w</a>');
document.writeln('                                        <a href="products.html">2400w</a>');
document.writeln('                                        <a href="products.html">3500w</a>');
document.writeln('                                    </div>');
document.writeln('                                </div>                      ');
document.writeln('                            </div>');
document.writeln('');
document.writeln('                        </div>');
document.writeln('                    </div>');
document.writeln('                    <a href="question.html">常見問題</a>');
document.writeln('                    <a href="contact.html">聯絡我們</a>');
document.writeln('                </div>            ');
document.writeln('            </div>      ');
document.writeln('');
document.writeln('            <div class="header-right">');
document.writeln('                <div class="header-icon search">');
document.writeln('                    <div class="search-icon show-1200"><img src="SRC/images/search.svg"></div>');
document.writeln('                    <div class="search-box">');
document.writeln('                        <form class="search-bar" action="search.html">');
document.writeln('                            <div class="search-close"><span>X</span>關閉</div>');
document.writeln('                            <input type="text" placeholder="請輸入產品名稱" name="search">');
document.writeln('                            <button type="submit">送出</button>');
document.writeln('');
document.writeln('                        </form>');
document.writeln('                    </div>');
document.writeln('                </div>');
document.writeln('                <div class="header-icon member-icon hide-1024">');
document.writeln('                    <a href="member_login.html"><img src="SRC/images/user.svg"></a>');
document.writeln('                    <ul class="member-hover">');
document.writeln('                        <li><a href="member_register.html">註冊</a></li>');
document.writeln('                        <li><a href="member_login.html">登入</a></li>');
document.writeln('                        ');
document.writeln('                    </ul>');
document.writeln('                </div>');
document.writeln('                ');
document.writeln('                <div class="header-icon header-cart hide-1024">');
document.writeln('                    <a href="shopcart.html"><img src="SRC/images/cart.svg"><span class="cart-num">1</span></a>');
document.writeln('                    <!-- 購物車 hover -->');
document.writeln('                    <div class="shop-hover">');
document.writeln('                        <div class="shop-hover-content">');
document.writeln('');
document.writeln('                            <div class="shop-item">');
document.writeln('                                <div class="shop-left">');
document.writeln('                                    <a href="product_detail.html"><img src="SRC/images/demo/pr1.jpg"></a>');
document.writeln('                                </div>');
document.writeln('                                <div class="shop-right">');
document.writeln('                                    <div>');
document.writeln('                                        <div class="s-discount">8折</div>');
document.writeln('                                    </div>');
document.writeln('                                    <a href="product_detail.html" class="name two-ellipsis">剪枝機特價 修枝機 鋰電 修籬機 21V 雙刃弧形修枝剪 牧田電池可 籬笆剪 單手剪 修枝剪 性價比</a>');
document.writeln('                                    <div class="text">數量<span>｜</span>1</div>');
document.writeln('                                    <div class="d-f">');
document.writeln('                                        <div class="price">');
document.writeln('                                          <span class="del">$9,999</span>');
document.writeln('                                            <span class="red">$2,099</span>  ');
document.writeln('                                        </div>');
document.writeln('                                        <i class="far fa-trash-alt"></i>');
document.writeln('                                    </div>');
document.writeln('                                        ');
document.writeln('                                </div>');
document.writeln('                               <!--  加購 -->');
document.writeln('                                <div class="shop-item add-item">');
document.writeln('                                    <div class="shop-left">');
document.writeln('                                        <a href="product_detail.html"><img src="SRC/images/demo/pr1.jpg"></a>');
document.writeln('                                    </div>');
document.writeln('                                    <div class="shop-right">');
document.writeln('                                            <div>');
document.writeln('                                                <div class="s-discount">8折</div><div class="gold-border">加購商品</div>');
document.writeln('                                            </div>');
document.writeln('                                            <a href="product_detail.html" class="name two-ellipsis">剪枝機特價 修枝機 鋰電 修籬機 21V 雙刃弧形修枝剪 牧田電池可 籬笆剪 單手剪 修枝剪 性價比</a>');
document.writeln('                                            <div class="text">數量<span>｜</span>1</div>');
document.writeln('                                            <div class="d-f">');
document.writeln('                                                <div class="price">');
document.writeln('                                                  <span class="del">$9,999</span>');
document.writeln('                                                    <span class="red">$2,099</span>  ');
document.writeln('                                                </div>');
document.writeln('                                                <i class="far fa-trash-alt"></i>');
document.writeln('                                            </div>');
document.writeln('                                    </div>');
document.writeln('                                </div>');
document.writeln('                            </div>');
document.writeln('                            <div class="shop-item">');
document.writeln('                                <div class="shop-left">');
document.writeln('                                    <a href="product_detail.html"><img src="SRC/images/demo/pr1.jpg"></a>');
document.writeln('                                </div>');
document.writeln('                                <div class="shop-right">');
document.writeln('                                        <div>');
document.writeln('                                            <div class="s-free">免運</div>');
document.writeln('                                        </div>');
document.writeln('                                        <a href="product_detail.html" class="name two-ellipsis">剪枝機特價 修枝機 鋰電 修籬機 21V 雙刃弧形修枝剪 牧田電池可 籬笆剪 單手剪 修枝剪 性價比</a>');
document.writeln('                                        <div class="text">數量<span>｜</span>1</div>');
document.writeln('                                        <div class="d-f">');
document.writeln('                                            <div class="price">');
document.writeln('                                              <span class="del">$9,999</span>');
document.writeln('                                                <span class="red">$2,099</span>  ');
document.writeln('                                            </div>');
document.writeln('                                            <i class="far fa-trash-alt"></i>');
document.writeln('                                        </div>');
document.writeln('                                </div>');
document.writeln('                            </div>');
document.writeln('                            <div class="shop-item">');
document.writeln('                                <div class="shop-left">');
document.writeln('                                    <a href="product_detail.html"><img src="SRC/images/demo/pr1.jpg"></a>');
document.writeln('                                </div>');
document.writeln('                                <div class="shop-right">');
document.writeln('                                    <a href="product_detail.html" class="name two-ellipsis">剪枝機特價 修枝機 鋰電 修籬機 21V 雙刃弧形修枝剪 牧田電池可 籬笆剪 單手剪 修枝剪 性價比</a>');
document.writeln('                                    <div class="text">數量<span>｜</span>1</div>');
document.writeln('                                    <div class="d-f">');
document.writeln('                                        <div class="price">');
document.writeln('                                          <span class="del">$9,999</span>');
document.writeln('                                            <span class="red">$2,099</span>  ');
document.writeln('                                        </div>');
document.writeln('                                        <i class="far fa-trash-alt"></i>');
document.writeln('                                    </div>');
document.writeln('                                </div>');
document.writeln('                            </div>                         ');
document.writeln('                        </div>');
document.writeln('                        <div class="shop-hover-total"><div>共<span>3</span>件，總計<span>$9,999</span></div><a href="shopcart.html">結帳</a></div>');
document.writeln('                    </div>');
document.writeln('                    <!-- 購物車 hover end-->');
document.writeln('                </div>');
document.writeln('                ');
document.writeln('            </div>');
document.writeln('        </div>');
document.writeln('        <div class="fast-menu show-1024"><a href="products.html">全部商品</a><a href="sale.html">活動專區</a><a href="news.html">最新消息</a><a href="question.html">常見問題</a></div>');
document.writeln('    </header>');
document.writeln('');
