document.writeln('<div class="mobile-menu">');
document.writeln('    <div class="mobile-menu-top">');
document.writeln('        <a class="m-menu-top-a" href="#box1">產品分類</a>');
document.writeln('        <a class="m-menu-top-a" href="#box2">活動專區</a>');
document.writeln('        <a class="m-menu-top-a" href="#box3">關於達利</a>');
document.writeln('        <div class="mobile-close">X</div>');
document.writeln('    </div>');
document.writeln('    <div id="box1" class="tab-box mobile-menu-prod">');
document.writeln('        <div class="mobile-menu-left">');
document.writeln('            <div class="m-menu-left-title"><div class="two-ellipsis"><a href="#class1">品牌分類</a></div></div>');
document.writeln('            <div class="m-menu-left-title"><div class="two-ellipsis"><a href="#class2">電動工具</a></div></div>');
document.writeln('            <div class="m-menu-left-title"><div class="two-ellipsis"><a href="#class3">氣動工具</a></div></div>');
document.writeln('            <div class="m-menu-left-title"><div class="two-ellipsis"><a href="#class4">農機具</a></div></div>');
document.writeln('            <div class="m-menu-left-title"><div class="two-ellipsis"><a href="#class5">發電機</a></div></div>');
document.writeln('        </div>');
document.writeln('        <div class="mobile-menu-right">');
document.writeln('            <div id="class1" class="m-menu-box">    ');
document.writeln('                <a href="products.html" class="m-menu-box-title fas">機台</a>');
document.writeln('                <div class="mobile-scroll">');
document.writeln('                    <a class="m-menu-box-class" href="products.html">');
document.writeln('                        <img class="m-menu-box-pic" src="SRC/images/demo/p3.jpg">');
document.writeln('                        <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                    </a>');
document.writeln('                    <a class="m-menu-box-class" href="products.html">');
document.writeln('                        <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                        <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                    </a>');
document.writeln('                    <a class="m-menu-box-class" href="products.html">');
document.writeln('                        <img class="m-menu-box-pic" src="SRC/images/demo/p3.jpg">');
document.writeln('                        <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                    </a>');
document.writeln('                    <a class="m-menu-box-class" href="products.html">');
document.writeln('                        <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                        <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                    </a>');
document.writeln('                    <a class="m-menu-box-class" href="products.html">');
document.writeln('                        <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                        <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                    </a>                        ');
document.writeln('                </div>');
document.writeln('');
document.writeln('            </div>');
document.writeln('            <div id="class2" class="m-menu-box">');
document.writeln('                <a href="products.html" class="m-menu-box-title fas">電動工具</a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p2.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">110v</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p2.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">110v</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p2.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">110v</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p2.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">110v</div>');
document.writeln('                </a>');
document.writeln('            </div>');
document.writeln('            <div id="class3" class="m-menu-box">');
document.writeln('                <a href="products.html" class="m-menu-box-title fas">氣動工具</a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p3.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                </a>');
document.writeln('            </div>');
document.writeln('            <div id="class4" class="m-menu-box">');
document.writeln('                <a href="products.html" class="m-menu-box-title fas">農機具</a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">電動割草機</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">電動割草機</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">電動割草機</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">電動割草機</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">電動割草機</div>');
document.writeln('                </a>');
document.writeln('            </div>');
document.writeln('            <div id="class5" class="m-menu-box">');
document.writeln('                <a href="products.html" class="m-menu-box-title fas">發電機</a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p3.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                </a>');
document.writeln('            </div>');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('    <div id="box2" class="tab-box mobile-menu-prod">');
document.writeln('        <div class="mobile-menu-left">');
document.writeln('            <div class="m-menu-left-title"><div class="two-ellipsis"><a href="#sale1">新品上市</a> </div></div>');
document.writeln('            <div class="m-menu-left-title"><div class="two-ellipsis"><a href="#sale2">A+B組合優惠區</a></div></div>');
document.writeln('            <div class="m-menu-left-title"><div class="two-ellipsis"><a href="#sale3">雙12限定並買商品</a></div></div>');
document.writeln('            <div class="m-menu-left-title"><div class="two-ellipsis"><a href="#sale4">12/1~12/31限時85折</a></div></div>');
document.writeln('            <div class="m-menu-left-title"><div class="two-ellipsis"><a href="#sale5">歡慶聖誕節，專屬優惠</a></div></div>');
document.writeln('        </div>');
document.writeln('        <div class="mobile-menu-right">');
document.writeln('            <div id="sale1" class="m-menu-box">    ');
document.writeln('                <a href="products.html" class="m-menu-box-title fas">機台</a>');
document.writeln('                <div class="mobile-scroll">');
document.writeln('                    <a class="m-menu-box-class" href="products.html">');
document.writeln('                        <img class="m-menu-box-pic" src="SRC/images/demo/p3.jpg">');
document.writeln('                        <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                    </a>');
document.writeln('                    <a class="m-menu-box-class" href="products.html">');
document.writeln('                        <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                        <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                    </a>');
document.writeln('                    <a class="m-menu-box-class" href="products.html">');
document.writeln('                        <img class="m-menu-box-pic" src="SRC/images/demo/p3.jpg">');
document.writeln('                        <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                    </a>');
document.writeln('                    <a class="m-menu-box-class" href="products.html">');
document.writeln('                        <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                        <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                    </a>');
document.writeln('                    <a class="m-menu-box-class" href="products.html">');
document.writeln('                        <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                        <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                    </a>                        ');
document.writeln('                </div>');
document.writeln('');
document.writeln('            </div>');
document.writeln('            <div id="sale2" class="m-menu-box">');
document.writeln('                <a href="products.html" class="m-menu-box-title fas">電動工具</a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p2.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">110v</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p2.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">110v</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p2.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">110v</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p2.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">110v</div>');
document.writeln('                </a>');
document.writeln('            </div>');
document.writeln('            <div id="sale3" class="m-menu-box">');
document.writeln('                <a href="products.html" class="m-menu-box-title fas">氣動工具</a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p3.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                </a>');
document.writeln('            </div>');
document.writeln('            <div id="sale4" class="m-menu-box">');
document.writeln('                <a href="products.html" class="m-menu-box-title fas">農機具</a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">電動割草機</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">電動割草機</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">電動割草機</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">電動割草機</div>');
document.writeln('                </a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p1.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">電動割草機</div>');
document.writeln('                </a>');
document.writeln('            </div>');
document.writeln('            <div id="sale5" class="m-menu-box">');
document.writeln('                <a href="products.html" class="m-menu-box-title fas">發電機</a>');
document.writeln('                <a class="m-menu-box-class" href="products.html">');
document.writeln('                    <img class="m-menu-box-pic" src="SRC/images/demo/p3.jpg">');
document.writeln('                    <div class="m-menu-box-name two-ellipsis">名稱</div>');
document.writeln('                </a>');
document.writeln('            </div>');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('    <div id="box3" class="tab-box mobile-menu-other">');
document.writeln('        <a href="about.html">公司介紹</a><a href="news.html">最新消息</a><a href="question.html">常見問題</a><a href="contact.html">聯絡我們</a>');
document.writeln('    </div>  ');
document.writeln('</div>');
