document.write("<!DOCTYPE html>");
document.write("<html lang=\"zh-Hant-TW\">");
document.write("<head>");
document.write("<meta charset=\"UTF-8\">");
document.write("<meta name=\"viewport\" content=\"width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=yes\" \/>");
document.write("<title>捷羚機械<\/title>");
document.write("");
document.write("<link href=\"css\/normalize.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"css\/layout.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"js\/venobox\/venobox.min.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("");
document.write("<link href=\"css\/form.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"css\/font.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"css\/fontawesome-all.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"css\/feather-icons.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"css\/animate.min.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.write("<link href=\"css\/menu.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link href=\"css\/master.css\" rel=\"stylesheet\" type=\"text\/css\" \/>");
document.write("<link rel=\"shortcut icon\" href=\"images\/favicon\/favicon.png\" type=\"image\/x-icon\">");
document.write("<link rel=\"icon\" href=\"images\/favicon\/favicon.png\" type=\"image\/x-icon\">");
document.write("<meta name=\"msapplication-TileColor\" content=\"#ffffff\">");
document.write("<meta name=\"theme-color\" content=\"#ffffff\">");
document.write("");
document.write("<\/head>");
document.write("<body>");
document.write("<!--wrapper-->");
document.write("<div id=\"wrapper\">");
document.write("  <header> ");
document.write("    <div class=\"pageHeader\"> ");
document.write("      <div class=\"box-top\">");
document.write("        <div class=\"logo\"><h1><a href=\"index.html\"><img src=\"images\/logo.svg\" alt=\"捷羚機械\" title=\"捷羚機械\"><\/a><\/h1><\/div>");
document.write("        <!--web menu -->");
document.write("        <nav class=\"menubox\">");
document.write("          <ul class=\"nav-menu\">");
document.write("            <li><a href=\"about.html\" class=\"nav-active\">關於我們<\/a>");
document.write("              <ul>");
document.write("                <li><a href=\"about.html\">公司簡介<\/a><\/li>");
document.write("                <li><a href=\"about.html\">新增分類<\/a><\/li>");
document.write("              <\/ul>");
document.write("            <\/li>");
document.write("            <li><a href=\"products.html\">產品系列<\/a>");
document.write("              <ul>");
document.write("                <li><a href=\"products.html\">JS系列<\/a><\/li>");
document.write("                <li><a href=\"products.html\">JL系列<\/a><\/li>");
document.write("                <li><a href=\"p_contatc.html\">產品洽詢<\/a><\/li>");
document.write("              <\/ul>");
document.write("            <\/li>");
document.write("            <li><a href=\"news.html\">最新消息<\/a>");
document.write("              <ul>");
document.write("                <li><a href=\"news.html\">最新消息<\/a><\/li>");
document.write("                <li><a href=\"news.html\">新聞發布動態<\/a><\/li>");
document.write("                <li><a href=\"news.html\">知識訊息<\/a><\/li>");
document.write("              <\/ul>");
document.write("            <\/li>");
document.write("            <li><a href=\"download.html\">檔案下載<\/a><\/li>");
document.write("            <li><a href=\"faq.html\">常見問題<\/a><\/li>");
document.write("            <li><a href=\"video.html\">影音專區<\/a><\/li>");
document.write("            <li><a href=\"contact.html\">聯絡資訊<\/a><\/li>");
document.write("          <\/ul>");
document.write("        <\/nav>");
document.write("        <div class=\"setHeader\">");
document.write("            <div class=\"search\">");
document.write("              <img src=\"images\/search.svg\">");
document.write("              <form action=\"search.html\">");
document.write("                <div class=\"box-top\">");
document.write("                  <input type=\"text\" placeholder=\"請輸入搜尋關鍵字\" class=\"bo-radius05 fc-c wc100\" name=\"searchtext1\">");
document.write("                  <a href=\"search.html\" class=\"search-btn\">搜 尋<\/a>                  ");
document.write("                <\/div>");
document.write("");
document.write("              <\/form>");
document.write("            <\/div>");
document.write("            <div class=\"lang-box\">");
document.write("              <img src=\"images\/lang.svg\">");
document.write("              <div class=\"lang-drop\">");
document.write("                 <div class=\"box-top\">");
document.write("                  <a href=\"\" class=\"active\">繁中<\/a>");
document.write("                  <a href=\"\">英文<\/a> ");
document.write("                 <\/div>   ");
document.write("              <\/div>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("        <!--\/\/web menu --> ");
document.write("        <!--moblie menu -->");
document.write("        <a href=\"javascript:;\" class=\"menu-btn\">");
document.write("            <span><\/span>");
document.write("            <span><\/span>");
document.write("            <span><\/span>");
document.write("        <\/a>");
document.write("        <section class=\"menu\">");
document.write("          <div class=\"scrollbar-inner\">");
document.write("            <ul class=\"main-list\">");
document.write("              <li class=\"more\">");
document.write("                <a href=\"about.html\">關於我們<\/a>");
document.write("                <ul class=\"sub-list\">");
document.write("                  <li><a href=\"about.html\">公司簡介<\/a><\/li>");
document.write("                  <li><a href=\"about.html\">新增分類<\/a><\/li>  ");
document.write("                <\/ul>");
document.write("              <\/li>");
document.write("              <li class=\"more\">");
document.write("                <a href=\"products.html\">產品系列<\/a>");
document.write("                <ul class=\"sub-list\">");
document.write("                  <li><a href=\"products.html\">JS系列<\/a><\/li>");
document.write("                  <li><a href=\"products.html\">JL系列<\/a><\/li>");
document.write("                  <li><a href=\"p_contatc.html\">產品洽詢<\/a><\/li>");
document.write("                <\/ul>");
document.write("              <\/li>");
document.write("              <li class=\"more\">");
document.write("                <a href=\"news.html\">最新消息<\/a>");
document.write("                <ul class=\"sub-list\">");
document.write("                  <li><a href=\"news.html\">最新消息<\/a><\/li>");
document.write("                  <li><a href=\"news.html\">新聞發布動態<\/a><\/li>");
document.write("                  <li><a href=\"news.html\">知識訊息<\/a><\/li>");
document.write("                <\/ul>");
document.write("              <\/li>");
document.write("              <li><a href=\"download.html\">檔案下載<\/a><\/li>");
document.write("              <li><a href=\"faq.html\">常見問題<\/a><\/li>");
document.write("              <li><a href=\"video.html\">影音專區<\/a><\/li>");
document.write("              <li><a href=\"contact.html\">聯絡資訊<\/a><\/li>");
document.write("            <\/ul>");
document.write("          <\/div>");
document.write("        <\/section>");
document.write("        <!--\/\/moblie menu -->");
document.write("      <\/div>  ");
document.write("    <\/div> ");
document.write("  <\/header>");
document.write("");
document.write("  <div class=\"mask-bg\"><\/div>");
document.write("  <div class=\"mask-bg2\"><\/div>");
